//! Model metadata, registry, and catalog loading.
//!
//! Defines the static catalog of known models and the lookup surface used
//! by the rest of the codebase. The registry has no runtime network
//! dependency: it is populated at startup from a JSON catalog, either the
//! bundled seed compiled into the binary via `include_str!` or an
//! optional user cache at `~/.aj/models.json` written by the catalog
//! refresh CLI. Overrides from the bundled `overrides.json` are applied
//! on top of whichever catalog loads, so authored corrections survive
//! refreshes.
//!
//! See `docs/models-spec.md` §3 for the full design.

use std::collections::HashMap;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::types::Usage;

/// Bundled seed, generated by the catalog refresh process. Always
/// present; guarantees the registry loads on first run, offline, or when
/// models.dev is unreachable. Updated by running the refresh command and
/// committing the resulting JSON.
const SEED_MODELS_JSON: &str = include_str!("../data/models.json");

/// Bundled overrides. Corrects known upstream inaccuracies and supplies
/// fields models.dev does not carry (`supports_xhigh`,
/// `supports_adaptive_thinking`). Applied on every load — seed and user
/// cache alike.
const OVERRIDES_JSON: &str = include_str!("../data/overrides.json");

/// Maximum allowed catalog age before the registry warns the user.
/// 90 days is a compromise — pricing changes on the order of months and
/// new models ship every few weeks; tighter thresholds would warn too
/// often on stable catalogs.
const STALENESS_THRESHOLD_DAYS: i64 = 90;

// ============================================================================
// §3.1 Model Metadata
// ============================================================================

/// Supported input modality. Matches the lowercase string form used by
/// the catalog JSON ("text" / "image").
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum InputModality {
    Text,
    Image,
}

/// Per-million-token cost rates for a model.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct ModelCost {
    pub input: f64,
    pub output: f64,
    pub cache_read: f64,
    pub cache_write: f64,
}

/// Static metadata for a known model. Each entry is the result of
/// merging a catalog entry with any matching overrides.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ModelInfo {
    /// Model identifier sent to the API (e.g. "claude-sonnet-4-20250514").
    pub id: String,
    /// Human-readable name (e.g. "Claude Sonnet 4").
    pub name: String,
    /// API type. One of "anthropic-messages", "openai-completions", or
    /// "openai-responses". Each `(provider, id)` pair has exactly one
    /// `api` — there is no duplication.
    pub api: String,
    /// Provider name (e.g. "anthropic", "openai").
    pub provider: String,
    /// Base URL for API requests.
    pub base_url: String,
    /// Whether the model supports extended thinking / reasoning.
    pub reasoning: bool,
    /// Whether the model supports the XHigh reasoning level (mapped to
    /// Anthropic `output_config: {effort: "max"}` or OpenAI
    /// `reasoning_effort: "xhigh"`). Populated by the catalog
    /// (seed + overrides); models.dev does not carry this flag.
    /// `false` for non-reasoning models.
    #[serde(default)]
    pub supports_xhigh: bool,
    /// Whether the model uses Anthropic's adaptive thinking API
    /// (`thinking: {type: "adaptive"}` + `output_config: {effort: ...}`)
    /// instead of the older budget-based thinking. Also governs whether
    /// the `interleaved-thinking-2025-05-14` beta header is sent —
    /// adaptive models have interleaved thinking built in and either
    /// reject or ignore the header. `false` for non-Anthropic and older
    /// Anthropic reasoning models.
    #[serde(default)]
    pub supports_adaptive_thinking: bool,
    /// Supported input modalities.
    pub input: Vec<InputModality>,
    /// Pricing per million tokens.
    pub cost: ModelCost,
    /// Maximum context window in tokens.
    pub context_window: u64,
    /// Maximum output tokens.
    pub max_tokens: u64,
    /// Optional extra HTTP headers the client should send (e.g. for
    /// providers like Copilot/Kimi that require static identity headers).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<HashMap<String, String>>,
}

// ============================================================================
// Catalog file schema (§3.4.1)
// ============================================================================

/// On-disk catalog format shared by the bundled seed and the user cache.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Catalog {
    /// Unix milliseconds when the catalog was last refreshed. Drives the
    /// staleness warning.
    pub updated_at: i64,
    /// Origin label (e.g. "models.dev"). Free-form; informational.
    pub source: String,
    pub models: Vec<ModelInfo>,
}

// ============================================================================
// Overrides file schema (§3.4.4)
// ============================================================================

/// On-disk overrides file. Each entry targets one `(provider, id)` pair
/// and shallow-merges the patch fields onto the matched model.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct OverridesFile {
    pub overrides: Vec<OverrideEntry>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct OverrideEntry {
    pub target: OverrideTarget,
    pub patch: OverridePatch,
    /// Required free-form rationale; surfaces to anyone reviewing the
    /// overrides file later.
    pub reason: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct OverrideTarget {
    pub provider: String,
    pub id: String,
}

/// Shallow-merge patch over a [`ModelInfo`]. Each `Option` is leave-alone
/// when `None` and replace-whole when `Some`. Nested objects (`cost`,
/// `input`) are replaced wholesale, not deep-merged — predictable wins
/// over clever.
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct OverridePatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supports_xhigh: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supports_adaptive_thinking: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input: Option<Vec<InputModality>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost: Option<ModelCost>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context_window: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<HashMap<String, String>>,
}

// ============================================================================
// §3.2 Registry
// ============================================================================

/// In-memory registry of all known models, organized by provider.
///
/// Built from a [`Catalog`] (seed or user cache) plus an
/// [`OverridesFile`]. Lookups are O(1) by `(provider, id)`; listing
/// preserves catalog order so output is stable.
#[derive(Clone, Debug)]
pub struct ModelRegistry {
    /// `provider -> id -> ModelInfo`, for O(1) lookups.
    by_provider: HashMap<String, HashMap<String, ModelInfo>>,
    /// First-seen provider order, for deterministic listing.
    provider_order: Vec<String>,
    /// First-seen model id order per provider, for deterministic listing.
    model_order: HashMap<String, Vec<String>>,
    /// Free-form label describing where the active catalog came from
    /// (e.g. "bundled seed", "user cache <path>"). Surfaced only in
    /// diagnostic output.
    source_label: String,
    /// `updated_at` from the catalog, retained for staleness logic and
    /// inspection.
    pub updated_at: i64,
}

impl ModelRegistry {
    /// Load the registry from the canonical sources, in priority order:
    ///
    /// 1. User cache at `~/.aj/models.json` if present and parseable.
    /// 2. Bundled seed at `data/models.json` (always available).
    ///
    /// Overrides from the bundled `data/overrides.json` are applied on
    /// top of the chosen catalog. Emits a one-line warning via `tracing`
    /// when the active catalog is older than [`STALENESS_THRESHOLD_DAYS`].
    pub fn load() -> Self {
        let (catalog, source) = load_active_catalog();
        let overrides = bundled_overrides();
        Self::from_catalog_with_overrides(catalog, overrides, source)
    }

    /// Build a registry from a known catalog + overrides set. Useful for
    /// tests and for callers that have already obtained their data
    /// out-of-band.
    pub fn from_catalog_with_overrides(
        catalog: Catalog,
        overrides: OverridesFile,
        source_label: impl Into<String>,
    ) -> Self {
        let mut models = catalog.models;
        // Apply overrides in declared order. Each entry shallow-merges
        // its patch onto the first matching `(provider, id)`.
        for entry in &overrides.overrides {
            apply_override(&mut models, entry);
        }

        let mut by_provider: HashMap<String, HashMap<String, ModelInfo>> = HashMap::new();
        let mut provider_order: Vec<String> = Vec::new();
        let mut model_order: HashMap<String, Vec<String>> = HashMap::new();

        for model in models {
            if !by_provider.contains_key(&model.provider) {
                provider_order.push(model.provider.clone());
                model_order.insert(model.provider.clone(), Vec::new());
            }
            let provider_map = by_provider.entry(model.provider.clone()).or_default();
            if !provider_map.contains_key(&model.id) {
                model_order
                    .get_mut(&model.provider)
                    .expect("inserted above")
                    .push(model.id.clone());
            }
            // Last write wins on duplicate `(provider, id)` — overrides
            // and catalogs alike rely on uniqueness, but this keeps the
            // registry deterministic if a stray duplicate slips through.
            provider_map.insert(model.id.clone(), model);
        }

        let registry = Self {
            by_provider,
            provider_order,
            model_order,
            source_label: source_label.into(),
            updated_at: catalog.updated_at,
        };
        registry.maybe_warn_stale();
        registry
    }

    /// Emit a `tracing::warn!` if the active catalog is older than the
    /// staleness threshold. Skipped silently for `updated_at <= 0` so
    /// callers can suppress the warning by zeroing the field (used in
    /// tests).
    fn maybe_warn_stale(&self) {
        if self.updated_at <= 0 {
            return;
        }
        let now_ms = chrono::Utc::now().timestamp_millis();
        let age_ms = now_ms.saturating_sub(self.updated_at);
        let age_days = age_ms / (1000 * 60 * 60 * 24);
        if age_days > STALENESS_THRESHOLD_DAYS {
            tracing::warn!(
                "model catalog ({}) is {} days old; run `aj models update` to refresh",
                self.source_label,
                age_days
            );
        }
    }

    /// Look up a model by `(provider, id)`. Returns `None` if either is
    /// unknown.
    pub fn get(&self, provider: &str, model_id: &str) -> Option<&ModelInfo> {
        self.by_provider.get(provider).and_then(|m| m.get(model_id))
    }

    /// List all known providers in stable insertion order.
    pub fn providers(&self) -> Vec<&str> {
        self.provider_order.iter().map(String::as_str).collect()
    }

    /// List all known models for a provider in stable insertion order.
    /// Returns an empty vec for unknown providers.
    pub fn models(&self, provider: &str) -> Vec<&ModelInfo> {
        let Some(ids) = self.model_order.get(provider) else {
            return Vec::new();
        };
        let Some(map) = self.by_provider.get(provider) else {
            return Vec::new();
        };
        ids.iter().filter_map(|id| map.get(id)).collect()
    }

    /// Diagnostic label describing the active catalog source. Useful
    /// in error messages and CLI output.
    pub fn source_label(&self) -> &str {
        &self.source_label
    }
}

// ============================================================================
// §3.3 Cost Calculation
// ============================================================================

/// Compute dollar costs per token category and the running total, and
/// store them in `usage.cost`. Rates in `model.cost` are
/// dollars-per-million-tokens; the function divides through by 1e6.
//
// `u64 → f64` is exact for any value below 2^53; token counts stay
// safely below that ceiling, so the `as` cast loses no precision in
// practice. There's no stable safe converter for this direction in
// std.
#[allow(clippy::as_conversions)]
pub fn calculate_cost(model: &ModelInfo, usage: &mut Usage) {
    const PER_MILLION: f64 = 1_000_000.0;
    usage.cost.input = (model.cost.input / PER_MILLION) * usage.input as f64;
    usage.cost.output = (model.cost.output / PER_MILLION) * usage.output as f64;
    usage.cost.cache_read = (model.cost.cache_read / PER_MILLION) * usage.cache_read as f64;
    usage.cost.cache_write = (model.cost.cache_write / PER_MILLION) * usage.cache_write as f64;
    usage.cost.total =
        usage.cost.input + usage.cost.output + usage.cost.cache_read + usage.cost.cache_write;
}

// ============================================================================
// §3.3.1 Capability Probes
// ============================================================================

/// Structural equality of two models by `(provider, api, id)`. Two
/// `ModelInfo`s with identical identity but different metadata still
/// compare equal — identity, not state, is what cross-provider replay
/// cares about.
pub fn models_are_equal(a: &ModelInfo, b: &ModelInfo) -> bool {
    a.provider == b.provider && a.api == b.api && a.id == b.id
}

/// Whether the model supports the XHigh reasoning level. Thin accessor
/// over [`ModelInfo::supports_xhigh`]; wrapped as a function so provider
/// code reads `supports_xhigh(model)` regardless of future schema
/// changes (e.g. if the flag ever becomes derived).
pub fn supports_xhigh(model: &ModelInfo) -> bool {
    model.supports_xhigh
}

/// Whether the model uses Anthropic's adaptive thinking API. Thin
/// accessor over [`ModelInfo::supports_adaptive_thinking`].
pub fn supports_adaptive_thinking(model: &ModelInfo) -> bool {
    model.supports_adaptive_thinking
}

// ============================================================================
// Catalog loading internals
// ============================================================================

/// Pick the active catalog, in priority order:
///
/// 1. User cache at `~/.aj/models.json` if present and parseable.
/// 2. Bundled seed (always succeeds — a malformed seed is a build-time
///    bug we surface via panic).
///
/// A user cache that exists but fails to parse logs a warning and falls
/// through to the seed. A missing cache falls through silently.
fn load_active_catalog() -> (Catalog, String) {
    if let Some(path) = user_cache_path()
        && path.exists()
    {
        match std::fs::read_to_string(&path) {
            Ok(body) => match serde_json::from_str::<Catalog>(&body) {
                Ok(cat) => return (cat, format!("user cache {}", path.display())),
                Err(err) => tracing::warn!(
                    "failed to parse user catalog at {}: {err}; falling back to bundled seed",
                    path.display()
                ),
            },
            Err(err) => tracing::warn!(
                "failed to read user catalog at {}: {err}; falling back to bundled seed",
                path.display()
            ),
        }
    }

    let seed: Catalog = serde_json::from_str(SEED_MODELS_JSON)
        .expect("bundled models.json must be valid; check src/aj-models/data/models.json");
    (seed, "bundled seed".to_string())
}

/// Parse the bundled overrides. Failure here is non-fatal: we log a
/// warning and proceed with no overrides, so a malformed file at most
/// degrades cost/capability accuracy without bricking the registry.
pub fn bundled_overrides() -> OverridesFile {
    serde_json::from_str(OVERRIDES_JSON).unwrap_or_else(|err| {
        tracing::warn!("failed to parse bundled overrides.json: {err}; ignoring");
        OverridesFile { overrides: vec![] }
    })
}

/// Resolve the user-cache path (`~/.aj/models.json`). Returns `None` if
/// the home directory cannot be determined.
pub fn user_cache_path() -> Option<PathBuf> {
    let mut p = home_dir()?;
    p.push(".aj");
    p.push("models.json");
    Some(p)
}

/// Local `home_dir` helper. `std::env::home_dir` was un-deprecated in
/// 1.86 but still carries the `deprecated` attribute on older toolchains
/// we want to build on; the `allow` keeps us compatible without pulling
/// in the `dirs` crate for one lookup.
fn home_dir() -> Option<PathBuf> {
    #[allow(deprecated)]
    {
        std::env::home_dir()
    }
}

/// Apply a single override entry to the model list, in place. Targets
/// that don't match any model log at debug — overrides for unreleased
/// or removed models are common during a transition.
pub(crate) fn apply_override(models: &mut [ModelInfo], entry: &OverrideEntry) {
    let Some(model) = models
        .iter_mut()
        .find(|m| m.provider == entry.target.provider && m.id == entry.target.id)
    else {
        tracing::debug!(
            "override target {}/{} not found in catalog (skipping); reason: {}",
            entry.target.provider,
            entry.target.id,
            entry.reason
        );
        return;
    };

    let p = &entry.patch;
    if let Some(v) = &p.name {
        model.name = v.clone();
    }
    if let Some(v) = &p.api {
        model.api = v.clone();
    }
    if let Some(v) = &p.base_url {
        model.base_url = v.clone();
    }
    if let Some(v) = p.reasoning {
        model.reasoning = v;
    }
    if let Some(v) = p.supports_xhigh {
        model.supports_xhigh = v;
    }
    if let Some(v) = p.supports_adaptive_thinking {
        model.supports_adaptive_thinking = v;
    }
    if let Some(v) = &p.input {
        model.input = v.clone();
    }
    if let Some(v) = &p.cost {
        model.cost = v.clone();
    }
    if let Some(v) = p.context_window {
        model.context_window = v;
    }
    if let Some(v) = p.max_tokens {
        model.max_tokens = v;
    }
    if let Some(v) = &p.headers {
        model.headers = Some(v.clone());
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::Usage;

    fn sample_model(provider: &str, id: &str) -> ModelInfo {
        ModelInfo {
            id: id.into(),
            name: id.into(),
            api: "anthropic-messages".into(),
            provider: provider.into(),
            base_url: "https://example.invalid".into(),
            reasoning: false,
            supports_xhigh: false,
            supports_adaptive_thinking: false,
            input: vec![InputModality::Text],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.3,
                cache_write: 3.75,
            },
            context_window: 200_000,
            max_tokens: 64_000,
            headers: None,
        }
    }

    fn empty_overrides() -> OverridesFile {
        OverridesFile { overrides: vec![] }
    }

    #[test]
    fn registry_lookup_and_listing() {
        let cat = Catalog {
            // updated_at: 0 suppresses the staleness warning in tests.
            updated_at: 0,
            source: "test".into(),
            models: vec![
                sample_model("anthropic", "claude-x"),
                sample_model("anthropic", "claude-y"),
                sample_model("openai", "gpt-z"),
            ],
        };
        let reg = ModelRegistry::from_catalog_with_overrides(cat, empty_overrides(), "test");

        // Lookups
        assert!(reg.get("anthropic", "claude-x").is_some());
        assert!(reg.get("openai", "gpt-z").is_some());
        assert!(reg.get("openai", "gpt-missing").is_none());
        assert!(reg.get("nope", "x").is_none());

        // Stable ordering
        assert_eq!(reg.providers(), vec!["anthropic", "openai"]);
        let anthropic_ids: Vec<_> = reg
            .models("anthropic")
            .iter()
            .map(|m| m.id.as_str())
            .collect();
        assert_eq!(anthropic_ids, vec!["claude-x", "claude-y"]);
        assert!(reg.models("nope").is_empty());
    }

    #[test]
    fn overrides_shallow_merge() {
        let cat = Catalog {
            updated_at: 0,
            source: "test".into(),
            models: vec![sample_model("anthropic", "claude-opus")],
        };
        let overrides = OverridesFile {
            overrides: vec![OverrideEntry {
                target: OverrideTarget {
                    provider: "anthropic".into(),
                    id: "claude-opus".into(),
                },
                patch: OverridePatch {
                    supports_xhigh: Some(true),
                    supports_adaptive_thinking: Some(true),
                    cost: Some(ModelCost {
                        input: 5.0,
                        output: 25.0,
                        cache_read: 0.5,
                        cache_write: 6.25,
                    }),
                    ..Default::default()
                },
                reason: "test".into(),
            }],
        };
        let reg = ModelRegistry::from_catalog_with_overrides(cat, overrides, "test");
        let m = reg.get("anthropic", "claude-opus").unwrap();
        assert!(m.supports_xhigh);
        assert!(m.supports_adaptive_thinking);
        assert_eq!(m.cost.cache_read, 0.5);
        // Untouched fields remain.
        assert_eq!(m.context_window, 200_000);
        assert_eq!(m.input, vec![InputModality::Text]);
    }

    #[test]
    fn overrides_target_unknown_is_silent() {
        let cat = Catalog {
            updated_at: 0,
            source: "test".into(),
            models: vec![sample_model("anthropic", "real-model")],
        };
        let overrides = OverridesFile {
            overrides: vec![OverrideEntry {
                target: OverrideTarget {
                    provider: "anthropic".into(),
                    id: "ghost-model".into(),
                },
                patch: OverridePatch {
                    supports_xhigh: Some(true),
                    ..Default::default()
                },
                reason: "test".into(),
            }],
        };
        // Should not panic; the matching entry is preserved.
        let reg = ModelRegistry::from_catalog_with_overrides(cat, overrides, "test");
        assert!(reg.get("anthropic", "real-model").is_some());
        assert!(reg.get("anthropic", "ghost-model").is_none());
    }

    #[test]
    fn calculate_cost_basic() {
        let model = sample_model("anthropic", "claude-x");
        let mut usage = Usage {
            input: 1_000_000,
            output: 500_000,
            cache_read: 100_000,
            cache_write: 50_000,
            total_tokens: 0,
            cost: Default::default(),
        };
        calculate_cost(&model, &mut usage);
        assert!((usage.cost.input - 3.0).abs() < 1e-9);
        assert!((usage.cost.output - 7.5).abs() < 1e-9);
        assert!((usage.cost.cache_read - 0.03).abs() < 1e-9);
        assert!((usage.cost.cache_write - 0.1875).abs() < 1e-9);
        let expected_total = 3.0 + 7.5 + 0.03 + 0.1875;
        assert!((usage.cost.total - expected_total).abs() < 1e-9);
    }

    #[test]
    fn capability_probes() {
        let mut m = sample_model("anthropic", "x");
        assert!(!supports_xhigh(&m));
        assert!(!supports_adaptive_thinking(&m));
        m.supports_xhigh = true;
        m.supports_adaptive_thinking = true;
        assert!(supports_xhigh(&m));
        assert!(supports_adaptive_thinking(&m));
    }

    #[test]
    fn models_are_equal_identity_not_state() {
        let mut a = sample_model("anthropic", "claude-x");
        let mut b = sample_model("anthropic", "claude-x");
        // State diverges, identity doesn't.
        a.cost.input = 100.0;
        b.context_window = 1;
        assert!(models_are_equal(&a, &b));
        b.id = "claude-y".into();
        assert!(!models_are_equal(&a, &b));
    }

    /// The bundled seed and overrides are part of the binary; if either
    /// fails to parse the registry won't load. Regression-test that the
    /// committed JSON stays well-formed.
    #[test]
    fn bundled_seed_and_overrides_parse() {
        let seed: Catalog = serde_json::from_str(SEED_MODELS_JSON).expect("seed parses");
        let overrides: OverridesFile =
            serde_json::from_str(OVERRIDES_JSON).expect("overrides parse");
        // Seed must contain at least one Anthropic and one OpenAI model.
        assert!(seed.models.iter().any(|m| m.provider == "anthropic"));
        assert!(seed.models.iter().any(|m| m.provider == "openai"));
        // All seed entries must be on the two filtered providers
        // (§3.4.7).
        for m in &seed.models {
            assert!(
                m.provider == "anthropic" || m.provider == "openai",
                "unexpected provider {} in seed",
                m.provider
            );
        }
        // Every override target must reference a real seed entry
        // before we try to apply it. This catches typos at test time.
        for entry in &overrides.overrides {
            assert!(
                seed.models
                    .iter()
                    .any(|m| m.provider == entry.target.provider && m.id == entry.target.id),
                "override target {}/{} does not match any seed entry",
                entry.target.provider,
                entry.target.id
            );
        }
    }

    /// Loading the registry from the bundled seed must succeed and the
    /// overrides must take effect.
    #[test]
    fn load_real_registry_applies_overrides() {
        let reg = ModelRegistry::load();
        assert!(!reg.providers().is_empty());
        // Pick a model the overrides file flips: opus-4-7 should have
        // both flags set after override application.
        if let Some(m) = reg.get("anthropic", "claude-opus-4-7") {
            assert!(supports_xhigh(m), "opus-4-7 should support xhigh");
            assert!(
                supports_adaptive_thinking(m),
                "opus-4-7 should use adaptive thinking"
            );
        }
        // gpt-5.2 is OpenAI xhigh-capable per overrides.
        if let Some(m) = reg.get("openai", "gpt-5.2") {
            assert!(supports_xhigh(m), "gpt-5.2 should support xhigh");
        }
    }
}
