//! Model metadata, registry, and catalog loading.
//!
//! Defines the static catalog of known models and the lookup surface used
//! by the rest of the codebase. The registry has no runtime network
//! dependency: it is populated at startup from a JSON catalog, either the
//! bundled seed compiled into the binary via `include_str!` or an
//! optional user cache at `~/.aj/models.json` written by the catalog
//! refresh CLI. Overrides from the bundled `overrides.json` are applied
//! on top of whichever catalog loads, so authored corrections survive
//! refreshes.

use std::collections::HashMap;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::types::{ThinkingLevel, Usage};

/// Bundled seed, generated by the catalog refresh process. Always
/// present; guarantees the registry loads on first run, offline, or when
/// models.dev is unreachable. Updated by running the refresh command and
/// committing the resulting JSON.
const SEED_MODELS_JSON: &str = include_str!("../data/models.json");

/// Bundled overrides: shallow patches that correct known upstream
/// inaccuracies in the catalog, applied on every load (seed and user
/// cache alike). Currently empty; kept as the seam for authored
/// corrections when a source ships wrong data.
const OVERRIDES_JSON: &str = include_str!("../data/overrides.json");

/// Bundled OpenAI Codex seed. The `openai-codex` provider points at
/// the ChatGPT subscription backend (`chatgpt.com/backend-api`) and
/// is not enumerated by models.dev, so its model list is maintained
/// here alongside the overrides file. The list is
/// authoritative: refresh appends these entries to every fresh cache
/// (defensively filtering any upstream re-emission first), and load
/// splices them in so users on a stale cache or an older bundled seed
/// still see Codex models. Limits, pricing, and reasoning controls are
/// hand-curated from the Codex CLI's own model catalog (the ChatGPT
/// backend advertises no `none`/`minimal` effort, so those rungs are
/// intentionally absent), not from models.dev whose API entries carry a
/// different effort vocabulary.
const CODEX_SEED_JSON: &str = include_str!("../data/codex.json");

/// Provider id used to key Codex catalog entries. Exposed so the
/// refresh and load paths agree on the value used for filtering and
/// splicing.
pub const CODEX_PROVIDER_ID: &str = "openai-codex";

/// Maximum allowed catalog age before the registry warns the user.
/// 90 days is a compromise — pricing changes on the order of months and
/// new models ship every few weeks; tighter thresholds would warn too
/// often on stable catalogs.
const STALENESS_THRESHOLD_DAYS: i64 = 90;

// ============================================================================
// Model Metadata
// ============================================================================

/// Supported input modality. Matches the lowercase string form used by
/// the catalog JSON ("text" / "image").
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum InputModality {
    Text,
    Image,
}

/// A reasoning control a model exposes, mirroring the catalog source's
/// `reasoning_options` shape. Drives the thinking levels AJ offers and
/// validates, and (for Anthropic) whether the adaptive thinking API is
/// used. Refresh normalizes each source's vocabulary into this form.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ReasoningOption {
    /// Reasoning can be turned on or off, with no effort selection.
    Toggle,
    /// Reasoning effort is chosen from a fixed vocabulary. A
    /// [`ThinkingLevel::Off`] value means the model accepts an explicit
    /// "no reasoning" effort (upstream `"none"`).
    Effort { values: Vec<ThinkingLevel> },
    /// Reasoning is controlled by a token budget within `[min, max]`.
    /// Either bound may be absent when the source doesn't publish it.
    BudgetTokens {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        min: Option<u64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        max: Option<u64>,
    },
}

/// Per-million-token cost rates for a model.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct ModelCost {
    pub input: f64,
    pub output: f64,
    pub cache_read: f64,
    pub cache_write: f64,
    /// Context-based pricing tiers. Empty for flat-rate models.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tiers: Vec<ModelCostTier>,
}

/// A context-based pricing tier: a step function that replaces the base
/// [`ModelCost`] rates for the whole request once the request is large
/// enough. Tiers are not marginal, the selected tier's rates apply to
/// every token category of the entire request.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct ModelCostTier {
    /// Total input-side token threshold for this tier, compared against
    /// `input + cache_read + cache_write` of the request's usage. The
    /// tier applies when the total input-side usage is strictly greater
    /// than this value. Among all tiers that apply, the one with the
    /// largest `input_tokens_above` wins and its rates replace the base
    /// rates for the whole request. If two tiers share a threshold the
    /// later one in the list wins, but well-formed data has no such ties.
    pub input_tokens_above: u64,
    pub input: f64,
    pub output: f64,
    pub cache_read: f64,
    pub cache_write: f64,
}

/// Static metadata for a known model. Each entry is the result of
/// merging a catalog entry with any matching overrides.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ModelInfo {
    /// Model identifier sent to the API (e.g. "claude-sonnet-4-20250514").
    pub id: String,
    /// Human-readable name (e.g. "Claude Sonnet 4").
    pub name: String,
    /// API type. One of "anthropic-messages", "openai-completions", or
    /// "openai-responses". Each `(provider, id)` pair has exactly one
    /// `api` — there is no duplication.
    pub api: String,
    /// Provider name (e.g. "anthropic", "openai").
    pub provider: String,
    /// Base URL for API requests.
    pub base_url: String,
    /// Whether the model supports extended thinking / reasoning.
    pub reasoning: bool,
    /// The reasoning controls this model exposes, as published by the
    /// catalog source. Empty for non-reasoning models, and for
    /// reasoning models whose source advertises no verified control.
    /// Drives the thinking levels AJ offers and validates, and (via
    /// [`supports_adaptive_thinking`]) whether an Anthropic model uses
    /// the adaptive thinking API.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub reasoning_options: Vec<ReasoningOption>,
    /// Whether the model honours OpenAI's `text.verbosity` parameter
    /// (the answer-length knob, see [`crate::types::Verbosity`]). The
    /// gpt-5 family on the Responses / Codex wire supports it; older
    /// OpenAI models and non-OpenAI models do not. Gates whether a
    /// caller-set verbosity reaches the request: unsupported models
    /// silently ignore the knob rather than 400.
    ///
    /// Not in models.dev. Derived in the refresh mapper (the OpenAI
    /// gpt-5 family on `openai-responses`, and OpenRouter's
    /// `supported_parameters`), hand-set on the Codex seed, and
    /// pinnable per model via overrides. The serde default is `false`.
    #[serde(default)]
    pub supports_verbosity: bool,
    /// Supported input modalities.
    pub input: Vec<InputModality>,
    /// Pricing per million tokens.
    pub cost: ModelCost,
    /// Maximum context window in tokens.
    pub context_window: u64,
    /// Maximum output tokens.
    pub max_tokens: u64,
}

// ============================================================================
// Catalog file schema
// ============================================================================

/// Current on-disk catalog schema version. Bump it whenever the bundled
/// catalog must supersede an existing user cache: when [`ModelInfo`]'s
/// shape changes in a way that would load older caches with
/// silently-wrong data, or when the bundled seed carries corrected data
/// that the additive load-time Codex splice can't push into a cache that
/// already holds those entries. A user cache whose `schema_version`
/// differs is ignored in favour of the bundled seed (see
/// [`load_active_catalog`]), so an incompatible or stale cache is a clean
/// miss rather than a subtle bug.
pub const CATALOG_SCHEMA_VERSION: u32 = 2;

/// On-disk catalog format shared by the bundled seed and the user cache.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Catalog {
    /// Schema version of this file. Absent in pre-versioned caches, so
    /// the serde default of `0` never equals [`CATALOG_SCHEMA_VERSION`]
    /// and those caches are rejected on load.
    #[serde(default)]
    pub schema_version: u32,
    /// Unix milliseconds when the catalog was last refreshed. Drives the
    /// staleness warning.
    pub updated_at: i64,
    /// Origin label (e.g. "models.dev"). Free-form; informational.
    pub source: String,
    pub models: Vec<ModelInfo>,
}

// ============================================================================
// Overrides file schema
// ============================================================================

/// On-disk overrides file. Each entry targets one `(provider, id)` pair
/// and shallow-merges the patch fields onto the matched model.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct OverridesFile {
    pub overrides: Vec<OverrideEntry>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct OverrideEntry {
    pub target: OverrideTarget,
    pub patch: OverridePatch,
    /// Required free-form rationale; surfaces to anyone reviewing the
    /// overrides file later.
    pub reason: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct OverrideTarget {
    pub provider: String,
    pub id: String,
}

/// Shallow-merge patch over a [`ModelInfo`]. Each `Option` is leave-alone
/// when `None` and replace-whole when `Some`. Nested objects (`cost`,
/// `input`) are replaced wholesale, not deep-merged — predictable wins
/// over clever.
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct OverridePatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning_options: Option<Vec<ReasoningOption>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supports_verbosity: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input: Option<Vec<InputModality>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost: Option<ModelCost>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context_window: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u64>,
}

// ============================================================================
// Registry
// ============================================================================

/// In-memory registry of all known models, organized by provider.
///
/// Built from a [`Catalog`] (seed or user cache) plus an
/// [`OverridesFile`]. Lookups are O(1) by `(provider, id)`; listing
/// preserves catalog order so output is stable.
#[derive(Clone, Debug)]
pub struct ModelRegistry {
    /// `provider -> id -> ModelInfo`, for O(1) lookups.
    by_provider: HashMap<String, HashMap<String, ModelInfo>>,
    /// First-seen provider order, for deterministic listing.
    provider_order: Vec<String>,
    /// First-seen model id order per provider, for deterministic listing.
    model_order: HashMap<String, Vec<String>>,
    /// Free-form label describing where the active catalog came from
    /// (e.g. "bundled seed", "user cache <path>"). Surfaced only in
    /// diagnostic output.
    source_label: String,
    /// `updated_at` from the catalog, retained for staleness logic and
    /// inspection.
    pub updated_at: i64,
}

impl ModelRegistry {
    /// Load the registry from the canonical sources, in priority order:
    ///
    /// 1. User cache at `~/.aj/models.json` if present and parseable.
    /// 2. Bundled seed at `data/models.json` (always available).
    ///
    /// Overrides from the bundled `data/overrides.json` are applied on
    /// top of the chosen catalog. Emits a one-line warning via `tracing`
    /// when the active catalog is older than [`STALENESS_THRESHOLD_DAYS`].
    pub fn load() -> Self {
        let (catalog, source) = load_active_catalog();
        let overrides = bundled_overrides();
        Self::from_catalog_with_overrides(catalog, overrides, source)
    }

    /// Build a registry from a known catalog + overrides set. Useful for
    /// tests and for callers that have already obtained their data
    /// out-of-band.
    pub fn from_catalog_with_overrides(
        catalog: Catalog,
        overrides: OverridesFile,
        source_label: impl Into<String>,
    ) -> Self {
        let mut models = catalog.models;
        // Splice in the Codex seed before overrides run so authored
        // patches can target Codex models too. Entries already present
        // in the catalog (e.g. a freshly-refreshed user cache that
        // included them) are not duplicated; the splice is purely
        // additive for `(provider, id)` keys that aren't there yet.
        splice_codex_seed(&mut models, bundled_codex_seed());
        // Apply overrides in declared order. Each entry shallow-merges
        // its patch onto the first matching `(provider, id)`.
        for entry in &overrides.overrides {
            apply_override(&mut models, entry);
        }

        let mut by_provider: HashMap<String, HashMap<String, ModelInfo>> = HashMap::new();
        let mut provider_order: Vec<String> = Vec::new();
        let mut model_order: HashMap<String, Vec<String>> = HashMap::new();

        for model in models {
            if !by_provider.contains_key(&model.provider) {
                provider_order.push(model.provider.clone());
                model_order.insert(model.provider.clone(), Vec::new());
            }
            let provider_map = by_provider.entry(model.provider.clone()).or_default();
            if !provider_map.contains_key(&model.id) {
                model_order
                    .get_mut(&model.provider)
                    .expect("inserted above")
                    .push(model.id.clone());
            }
            // Last write wins on duplicate `(provider, id)` — overrides
            // and catalogs alike rely on uniqueness, but this keeps the
            // registry deterministic if a stray duplicate slips through.
            provider_map.insert(model.id.clone(), model);
        }

        let registry = Self {
            by_provider,
            provider_order,
            model_order,
            source_label: source_label.into(),
            updated_at: catalog.updated_at,
        };
        registry.maybe_warn_stale();
        registry
    }

    /// Emit a `tracing::warn!` if the active catalog is older than the
    /// staleness threshold. Skipped silently for `updated_at <= 0` so
    /// callers can suppress the warning by zeroing the field (used in
    /// tests).
    fn maybe_warn_stale(&self) {
        if self.updated_at <= 0 {
            return;
        }
        let now_ms = chrono::Utc::now().timestamp_millis();
        let age_ms = now_ms.saturating_sub(self.updated_at);
        let age_days = age_ms / (1000 * 60 * 60 * 24);
        if age_days > STALENESS_THRESHOLD_DAYS {
            tracing::warn!(
                "model catalog ({}) is {} days old; run `aj update-models` to refresh",
                self.source_label,
                age_days
            );
        }
    }

    /// Look up a model by `(provider, id)`. Returns `None` if either is
    /// unknown.
    pub fn get(&self, provider: &str, model_id: &str) -> Option<&ModelInfo> {
        self.by_provider.get(provider).and_then(|m| m.get(model_id))
    }

    /// List all known providers in stable insertion order.
    pub fn providers(&self) -> Vec<&str> {
        self.provider_order.iter().map(String::as_str).collect()
    }

    /// List all known models for a provider in stable insertion order.
    /// Returns an empty vec for unknown providers.
    pub fn models(&self, provider: &str) -> Vec<&ModelInfo> {
        let Some(ids) = self.model_order.get(provider) else {
            return Vec::new();
        };
        let Some(map) = self.by_provider.get(provider) else {
            return Vec::new();
        };
        ids.iter().filter_map(|id| map.get(id)).collect()
    }

    /// Diagnostic label describing the active catalog source. Useful
    /// in error messages and CLI output.
    pub fn source_label(&self) -> &str {
        &self.source_label
    }
}

// ============================================================================
// Cost Calculation
// ============================================================================

/// Compute dollar costs per token category and the running total, and
/// store them in `usage.cost`. Rates in `cost` are
/// dollars-per-million-tokens; the function divides through by 1e6.
///
/// When `cost` carries context-based tiers, the rate set is chosen up
/// front: the total input-side usage (`input + cache_read +
/// cache_write`) selects the highest tier whose `input_tokens_above` it
/// strictly exceeds, and that tier's rates replace the base rates for
/// every token category. With no matching tier the base rates apply.
/// The selected rates are applied to the usage tokens exactly once, so
/// the per-category math does not branch on whether a tier was chosen.
//
// `u64 → f64` is exact for any value below 2^53; token counts stay
// safely below that ceiling, so the `as` cast loses no precision in
// practice. There's no stable safe converter for this direction in
// std.
#[allow(clippy::as_conversions)]
pub fn calculate_cost(cost: &ModelCost, usage: &mut Usage) {
    const PER_MILLION: f64 = 1_000_000.0;

    let input_side = usage.input + usage.cache_read + usage.cache_write;
    let rates = cost
        .tiers
        .iter()
        .filter(|tier| tier.input_tokens_above < input_side)
        .max_by_key(|tier| tier.input_tokens_above)
        .map_or(
            (cost.input, cost.output, cost.cache_read, cost.cache_write),
            |tier| (tier.input, tier.output, tier.cache_read, tier.cache_write),
        );
    let (input_rate, output_rate, cache_read_rate, cache_write_rate) = rates;

    usage.cost.input = (input_rate / PER_MILLION) * usage.input as f64;
    usage.cost.output = (output_rate / PER_MILLION) * usage.output as f64;
    usage.cost.cache_read = (cache_read_rate / PER_MILLION) * usage.cache_read as f64;
    usage.cost.cache_write = (cache_write_rate / PER_MILLION) * usage.cache_write as f64;
    usage.cost.total =
        usage.cost.input + usage.cost.output + usage.cost.cache_read + usage.cost.cache_write;
}

// ============================================================================
// Capability Probes
// ============================================================================

/// Structural equality of two models by `(provider, api, id)`. Two
/// `ModelInfo`s with identical identity but different metadata still
/// compare equal — identity, not state, is what cross-provider replay
/// cares about.
pub fn models_are_equal(a: &ModelInfo, b: &ModelInfo) -> bool {
    a.provider == b.provider && a.api == b.api && a.id == b.id
}

/// Whether the model uses Anthropic's adaptive thinking API
/// (`thinking: {type: "adaptive"}` + `output_config: {effort}`) rather
/// than budget-based thinking.
///
/// Derived: an Anthropic model that advertises an [`ReasoningOption::Effort`]
/// control. A model that only exposes a budget control (legacy
/// Anthropic) is budget-based. This also gates the
/// `interleaved-thinking-2025-05-14` beta, which adaptive models reject
/// or ignore.
pub fn supports_adaptive_thinking(model: &ModelInfo) -> bool {
    model.api == "anthropic-messages"
        && model
            .reasoning_options
            .iter()
            .any(|o| matches!(o, ReasoningOption::Effort { .. }))
}

/// Whether the model honours OpenAI's `text.verbosity` parameter.
/// Thin accessor over [`ModelInfo::supports_verbosity`].
pub fn supports_verbosity(model: &ModelInfo) -> bool {
    model.supports_verbosity
}

/// Validate a requested [`ThinkingLevel`] against a model's wire
/// vocabulary, returning a human-readable message when the level isn't
/// one the model offers.
///
/// aj sends the chosen effort verbatim, with no remapping, flooring, or
/// ceiling, so the level must be a member of
/// [`supported_thinking_levels`] for this model. A non-reasoning model
/// offers only `off`, and asking for any effort on it is an error rather
/// than a silent no-op.
pub fn validate_thinking_level(model: &ModelInfo, level: &ThinkingLevel) -> Result<(), String> {
    let supported = supported_thinking_levels(model);
    if supported.contains(level) {
        return Ok(());
    }
    let offered = supported
        .iter()
        .map(ThinkingLevel::as_str)
        .collect::<Vec<_>>()
        .join(", ");
    Err(format!(
        "model '{}' does not support thinking level '{}'; supported: {offered}",
        model.id,
        level.as_str(),
    ))
}

/// Every thinking level in canonical, cheapest-first order. Offered sets
/// are returned as a subset of this, so callers get a stable order.
const ALL_THINKING_LEVELS: [ThinkingLevel; 7] = [
    ThinkingLevel::Off,
    ThinkingLevel::Minimal,
    ThinkingLevel::Low,
    ThinkingLevel::Medium,
    ThinkingLevel::High,
    ThinkingLevel::XHigh,
    ThinkingLevel::Max,
];

/// The exact thinking levels a model offers, in canonical order. This is
/// the single source of truth for both the selector UI and
/// [`validate_thinking_level`].
///
/// The rules, in order:
///
/// - A non-reasoning model offers only `off`.
/// - An `Effort` control contributes its advertised levels verbatim, and
///   a `Toggle` control contributes `off`.
/// - Anthropic extended thinking is opt-in, so every reasoning Anthropic
///   model can also run with thinking `off`, regardless of its effort
///   enum (which names only the levels used while thinking is on).
/// - A reasoning model with no `Effort` control (budget-only,
///   toggle-only, or no controls at all) has no effort vocabulary to be
///   exact about, so it falls back to the full ladder and lets the
///   provider surface any level it can't honour.
pub fn supported_thinking_levels(model: &ModelInfo) -> Vec<ThinkingLevel> {
    if !model.reasoning {
        return vec![ThinkingLevel::Off];
    }

    let mut offered: Vec<ThinkingLevel> = Vec::new();
    let mut has_effort = false;
    for option in &model.reasoning_options {
        match option {
            ReasoningOption::Effort { values } => {
                has_effort = true;
                offered.extend(values.iter().copied());
            }
            ReasoningOption::Toggle => offered.push(ThinkingLevel::Off),
            // A token budget accepts any effort; the no-effort fallback
            // below turns that into the full ladder.
            ReasoningOption::BudgetTokens { .. } => {}
        }
    }

    if model.api == "anthropic-messages" {
        offered.push(ThinkingLevel::Off);
    }

    // No effort vocabulary to be exact about (budget-only, toggle-only,
    // or no controls at all): offer the full ladder.
    if !has_effort {
        return ALL_THINKING_LEVELS.to_vec();
    }

    let levels: Vec<ThinkingLevel> = ALL_THINKING_LEVELS
        .iter()
        .copied()
        .filter(|level| offered.contains(level))
        .collect();
    // An effort control normally maps at least one level, but an empty
    // or all-unknown effort enum (only reachable via a hand-edited
    // override) would leave nothing. Fall back to the full ladder so the
    // returned set is never empty and reasoning stays reachable.
    if levels.is_empty() {
        return ALL_THINKING_LEVELS.to_vec();
    }
    levels
}

// ============================================================================
// Catalog loading internals
// ============================================================================

/// Pick the active catalog, in priority order:
///
/// 1. User cache at `~/.aj/models.json` if present and parseable.
/// 2. Bundled seed (always succeeds — a malformed seed is a build-time
///    bug we surface via panic).
///
/// A user cache that exists but fails to parse logs a warning and falls
/// through to the seed. A missing cache falls through silently.
fn load_active_catalog() -> (Catalog, String) {
    if let Some(path) = user_cache_path()
        && path.exists()
    {
        match std::fs::read_to_string(&path) {
            Ok(body) => match serde_json::from_str::<Catalog>(&body) {
                Ok(cat) if cat.schema_version == CATALOG_SCHEMA_VERSION => {
                    return (cat, format!("user cache {}", path.display()));
                }
                Ok(cat) => tracing::warn!(
                    "user catalog at {} has schema version {} (expected {}); \
                     falling back to bundled seed (run `aj update-models` to refresh)",
                    path.display(),
                    cat.schema_version,
                    CATALOG_SCHEMA_VERSION
                ),
                Err(err) => tracing::warn!(
                    "failed to parse user catalog at {}: {err}; falling back to bundled seed",
                    path.display()
                ),
            },
            Err(err) => tracing::warn!(
                "failed to read user catalog at {}: {err}; falling back to bundled seed",
                path.display()
            ),
        }
    }

    let seed: Catalog = serde_json::from_str(SEED_MODELS_JSON)
        .expect("bundled models.json must be valid; check src/aj-models/data/models.json");
    (seed, "bundled seed".to_string())
}

/// Parse the bundled overrides. Failure here is non-fatal: we log a
/// warning and proceed with no overrides, so a malformed file at most
/// degrades cost/capability accuracy without bricking the registry.
pub fn bundled_overrides() -> OverridesFile {
    serde_json::from_str(OVERRIDES_JSON).unwrap_or_else(|err| {
        tracing::warn!("failed to parse bundled overrides.json: {err}; ignoring");
        OverridesFile { overrides: vec![] }
    })
}

/// On-disk shape of the bundled Codex seed file. Lives in its own
/// struct so the catalog and seed files don't share the
/// `updated_at`/`source` framing — the Codex list has no upstream and
/// no refresh timestamp.
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct CodexSeedFile {
    pub models: Vec<ModelInfo>,
}

/// Parse the bundled OpenAI Codex seed (`data/codex.json`). Failure
/// here is non-fatal: we log a warning and proceed with an empty list,
/// so a malformed file at most hides Codex models without bricking the
/// registry. Each entry must already carry
/// `provider == CODEX_PROVIDER_ID`; non-Codex entries are dropped with
/// a warning so the file can't accidentally inject other providers.
pub fn bundled_codex_seed() -> Vec<ModelInfo> {
    let parsed: CodexSeedFile = match serde_json::from_str(CODEX_SEED_JSON) {
        Ok(file) => file,
        Err(err) => {
            tracing::warn!("failed to parse bundled codex.json: {err}; ignoring");
            return Vec::new();
        }
    };
    parsed
        .models
        .into_iter()
        .filter(|m| {
            if m.provider == CODEX_PROVIDER_ID {
                true
            } else {
                tracing::warn!(
                    "codex.json entry {}/{} has unexpected provider; dropping",
                    m.provider,
                    m.id
                );
                false
            }
        })
        .collect()
}

/// Splice the Codex seed onto an existing model list, adding entries
/// for `(provider, id)` keys not already present and leaving existing
/// entries untouched. The catalog's prior contents win on conflict so
/// a user cache that already carries refreshed Codex models doesn't
/// have its values silently rewritten by the in-process seed.
///
/// Returns the number of entries appended; useful in diagnostics and
/// tests.
pub fn splice_codex_seed(models: &mut Vec<ModelInfo>, seed: Vec<ModelInfo>) -> usize {
    if seed.is_empty() {
        return 0;
    }
    let existing: std::collections::HashSet<(String, String)> = models
        .iter()
        .map(|m| (m.provider.clone(), m.id.clone()))
        .collect();
    let mut appended = 0;
    for entry in seed {
        if existing.contains(&(entry.provider.clone(), entry.id.clone())) {
            continue;
        }
        models.push(entry);
        appended += 1;
    }
    appended
}

/// Resolve the user-cache path (`~/.aj/models.json`). Returns `None` if
/// the home directory cannot be determined.
pub fn user_cache_path() -> Option<PathBuf> {
    let mut p = home_dir()?;
    p.push(".aj");
    p.push("models.json");
    Some(p)
}

/// Local `home_dir` helper. `std::env::home_dir` was un-deprecated in
/// 1.86 but still carries the `deprecated` attribute on older toolchains
/// we want to build on; the `allow` keeps us compatible without pulling
/// in the `dirs` crate for one lookup.
fn home_dir() -> Option<PathBuf> {
    #[allow(deprecated)]
    {
        std::env::home_dir()
    }
}

/// Apply a single override entry to the model list, in place. Targets
/// that don't match any model log at debug — overrides for unreleased
/// or removed models are common during a transition.
pub(crate) fn apply_override(models: &mut [ModelInfo], entry: &OverrideEntry) {
    let Some(model) = models
        .iter_mut()
        .find(|m| m.provider == entry.target.provider && m.id == entry.target.id)
    else {
        tracing::debug!(
            "override target {}/{} not found in catalog (skipping); reason: {}",
            entry.target.provider,
            entry.target.id,
            entry.reason
        );
        return;
    };

    let p = &entry.patch;
    if let Some(v) = &p.name {
        model.name = v.clone();
    }
    if let Some(v) = &p.api {
        model.api = v.clone();
    }
    if let Some(v) = &p.base_url {
        model.base_url = v.clone();
    }
    if let Some(v) = p.reasoning {
        model.reasoning = v;
    }
    if let Some(v) = &p.reasoning_options {
        model.reasoning_options = v.clone();
    }
    if let Some(v) = p.supports_verbosity {
        model.supports_verbosity = v;
    }
    if let Some(v) = &p.input {
        model.input = v.clone();
    }
    if let Some(v) = &p.cost {
        model.cost = v.clone();
    }
    if let Some(v) = p.context_window {
        model.context_window = v;
    }
    if let Some(v) = p.max_tokens {
        model.max_tokens = v;
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::Usage;

    fn sample_model(provider: &str, id: &str) -> ModelInfo {
        ModelInfo {
            id: id.into(),
            name: id.into(),
            api: "anthropic-messages".into(),
            provider: provider.into(),
            base_url: "https://example.invalid".into(),
            reasoning: false,
            reasoning_options: Vec::new(),
            supports_verbosity: false,
            input: vec![InputModality::Text],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.3,
                cache_write: 3.75,
                tiers: Vec::new(),
            },
            context_window: 200_000,
            max_tokens: 64_000,
        }
    }

    fn empty_overrides() -> OverridesFile {
        OverridesFile { overrides: vec![] }
    }

    #[test]
    fn registry_lookup_and_listing() {
        let cat = Catalog {
            schema_version: CATALOG_SCHEMA_VERSION,
            // updated_at: 0 suppresses the staleness warning in tests.
            updated_at: 0,
            source: "test".into(),
            models: vec![
                sample_model("anthropic", "claude-x"),
                sample_model("anthropic", "claude-y"),
                sample_model("openai", "gpt-z"),
            ],
        };
        let reg = ModelRegistry::from_catalog_with_overrides(cat, empty_overrides(), "test");

        // Lookups
        assert!(reg.get("anthropic", "claude-x").is_some());
        assert!(reg.get("openai", "gpt-z").is_some());
        assert!(reg.get("openai", "gpt-missing").is_none());
        assert!(reg.get("nope", "x").is_none());

        // Stable ordering. The bundled Codex seed splice appends
        // `openai-codex` after the explicit catalog providers when
        // the catalog itself doesn't carry the Codex entries.
        assert_eq!(reg.providers(), vec!["anthropic", "openai", "openai-codex"]);
        let anthropic_ids: Vec<_> = reg
            .models("anthropic")
            .iter()
            .map(|m| m.id.as_str())
            .collect();
        assert_eq!(anthropic_ids, vec!["claude-x", "claude-y"]);
        assert!(reg.models("nope").is_empty());

        // The codex splice fed entries; the registry surfaces them
        // under the codex provider with the codex api string.
        let codex_ids: Vec<_> = reg
            .models("openai-codex")
            .iter()
            .map(|m| m.id.as_str())
            .collect();
        assert!(!codex_ids.is_empty(), "codex seed populated");
        for m in reg.models("openai-codex") {
            assert_eq!(m.api, "openai-codex-responses");
            assert_eq!(m.base_url, "https://chatgpt.com/backend-api");
        }
    }

    #[test]
    fn overrides_shallow_merge() {
        let cat = Catalog {
            schema_version: CATALOG_SCHEMA_VERSION,
            updated_at: 0,
            source: "test".into(),
            models: vec![sample_model("anthropic", "claude-opus")],
        };
        let overrides = OverridesFile {
            overrides: vec![OverrideEntry {
                target: OverrideTarget {
                    provider: "anthropic".into(),
                    id: "claude-opus".into(),
                },
                patch: OverridePatch {
                    reasoning_options: Some(vec![ReasoningOption::Effort {
                        values: vec![ThinkingLevel::Low],
                    }]),
                    cost: Some(ModelCost {
                        input: 5.0,
                        output: 25.0,
                        cache_read: 0.5,
                        cache_write: 6.25,
                        tiers: Vec::new(),
                    }),
                    ..Default::default()
                },
                reason: "test".into(),
            }],
        };
        let reg = ModelRegistry::from_catalog_with_overrides(cat, overrides, "test");
        let m = reg.get("anthropic", "claude-opus").unwrap();
        // The Effort control the override installs makes the Anthropic
        // model derive as adaptive.
        assert!(supports_adaptive_thinking(m));
        assert_eq!(m.cost.cache_read, 0.5);
        // Untouched fields remain.
        assert_eq!(m.context_window, 200_000);
        assert_eq!(m.input, vec![InputModality::Text]);
    }

    #[test]
    fn overrides_target_unknown_is_silent() {
        let cat = Catalog {
            schema_version: CATALOG_SCHEMA_VERSION,
            updated_at: 0,
            source: "test".into(),
            models: vec![sample_model("anthropic", "real-model")],
        };
        let overrides = OverridesFile {
            overrides: vec![OverrideEntry {
                target: OverrideTarget {
                    provider: "anthropic".into(),
                    id: "ghost-model".into(),
                },
                patch: OverridePatch {
                    reasoning_options: Some(vec![ReasoningOption::Toggle]),
                    ..Default::default()
                },
                reason: "test".into(),
            }],
        };
        // Should not panic; the matching entry is preserved.
        let reg = ModelRegistry::from_catalog_with_overrides(cat, overrides, "test");
        assert!(reg.get("anthropic", "real-model").is_some());
        assert!(reg.get("anthropic", "ghost-model").is_none());
    }

    #[test]
    fn calculate_cost_basic() {
        let model = sample_model("anthropic", "claude-x");
        let mut usage = Usage {
            input: 1_000_000,
            output: 500_000,
            cache_read: 100_000,
            cache_write: 50_000,
            total_tokens: 0,
            cost: Default::default(),
        };
        calculate_cost(&model.cost, &mut usage);
        assert!((usage.cost.input - 3.0).abs() < 1e-9);
        assert!((usage.cost.output - 7.5).abs() < 1e-9);
        assert!((usage.cost.cache_read - 0.03).abs() < 1e-9);
        assert!((usage.cost.cache_write - 0.1875).abs() < 1e-9);
        let expected_total = 3.0 + 7.5 + 0.03 + 0.1875;
        assert!((usage.cost.total - expected_total).abs() < 1e-9);
    }

    /// A `ModelCost` with one context tier at 272k. Base rates are 1/1/1/1,
    /// the tier doubles them once the input side clears the threshold.
    fn tiered_cost() -> ModelCost {
        ModelCost {
            input: 1.0,
            output: 1.0,
            cache_read: 1.0,
            cache_write: 1.0,
            tiers: vec![ModelCostTier {
                input_tokens_above: 272_000,
                input: 2.0,
                output: 2.0,
                cache_read: 2.0,
                cache_write: 2.0,
            }],
        }
    }

    #[test]
    fn calculate_cost_tier_below_threshold_uses_base() {
        // input_side = 200_000 + 0 + 0, below the 272k threshold, so base
        // rates apply to every category.
        let cost = tiered_cost();
        let mut usage = Usage {
            input: 200_000,
            output: 100_000,
            cache_read: 0,
            cache_write: 0,
            total_tokens: 0,
            cost: Default::default(),
        };
        calculate_cost(&cost, &mut usage);
        assert!((usage.cost.input - 0.2).abs() < 1e-9);
        assert!((usage.cost.output - 0.1).abs() < 1e-9);
    }

    #[test]
    fn calculate_cost_tier_above_threshold_applies_to_all_categories() {
        // input_side = 200_000 + 50_000 + 30_000 = 280_000 > 272k, so the
        // tier's 2x rates apply to input, output, and both cache figures.
        let cost = tiered_cost();
        let mut usage = Usage {
            input: 200_000,
            output: 100_000,
            cache_read: 50_000,
            cache_write: 30_000,
            total_tokens: 0,
            cost: Default::default(),
        };
        calculate_cost(&cost, &mut usage);
        assert!((usage.cost.input - 0.4).abs() < 1e-9);
        assert!((usage.cost.output - 0.2).abs() < 1e-9);
        assert!((usage.cost.cache_read - 0.1).abs() < 1e-9);
        assert!((usage.cost.cache_write - 0.06).abs() < 1e-9);
    }

    #[test]
    fn calculate_cost_tier_boundary_is_strict() {
        // input_side exactly equals input_tokens_above, so the tier does
        // not fire (strict >). Base rates apply.
        let cost = tiered_cost();
        let mut usage = Usage {
            input: 272_000,
            output: 10_000,
            cache_read: 0,
            cache_write: 0,
            total_tokens: 0,
            cost: Default::default(),
        };
        calculate_cost(&cost, &mut usage);
        assert!((usage.cost.input - 0.272).abs() < 1e-9);
        assert!((usage.cost.output - 0.01).abs() < 1e-9);
    }

    #[test]
    fn calculate_cost_highest_matching_tier_wins() {
        // Two tiers. input_side clears both, so the higher threshold (and
        // its 5x rate) wins over the lower (3x). Tier order in the vec is
        // deliberately non-monotonic to prove selection is by value, not
        // position.
        let cost = ModelCost {
            input: 1.0,
            output: 1.0,
            cache_read: 1.0,
            cache_write: 1.0,
            tiers: vec![
                ModelCostTier {
                    input_tokens_above: 400_000,
                    input: 5.0,
                    output: 5.0,
                    cache_read: 5.0,
                    cache_write: 5.0,
                },
                ModelCostTier {
                    input_tokens_above: 272_000,
                    input: 3.0,
                    output: 3.0,
                    cache_read: 3.0,
                    cache_write: 3.0,
                },
            ],
        };
        let mut usage = Usage {
            input: 500_000,
            output: 100_000,
            cache_read: 0,
            cache_write: 0,
            total_tokens: 0,
            cost: Default::default(),
        };
        calculate_cost(&cost, &mut usage);
        assert!((usage.cost.input - 2.5).abs() < 1e-9);
        assert!((usage.cost.output - 0.5).abs() < 1e-9);
    }

    #[test]
    fn model_cost_serde_omits_empty_tiers() {
        let flat = ModelCost {
            input: 1.0,
            output: 2.0,
            cache_read: 0.5,
            cache_write: 1.0,
            tiers: Vec::new(),
        };
        let json = serde_json::to_string(&flat).expect("serializes");
        assert!(
            !json.contains("tiers"),
            "empty tiers must be omitted, got: {json}"
        );

        let tiered = tiered_cost();
        let round: ModelCost =
            serde_json::from_str(&serde_json::to_string(&tiered).expect("serializes"))
                .expect("deserializes");
        assert_eq!(round, tiered);
    }

    #[test]
    fn capability_probes() {
        let mut m = sample_model("anthropic", "x");
        assert!(!supports_adaptive_thinking(&m));
        m.reasoning_options = vec![ReasoningOption::Effort {
            values: vec![ThinkingLevel::Low, ThinkingLevel::High],
        }];
        assert!(supports_adaptive_thinking(&m));
    }

    #[test]
    fn reasoning_option_serde_round_trips() {
        // The catalog persists `reasoning_options`, so its on-disk shape
        // is a contract: `Off` must survive as `"off"` inside effort
        // values and absent budget bounds must be omitted.
        let opts = vec![
            ReasoningOption::Toggle,
            ReasoningOption::Effort {
                values: vec![ThinkingLevel::Off, ThinkingLevel::Low, ThinkingLevel::Max],
            },
            ReasoningOption::BudgetTokens {
                min: Some(1024),
                max: None,
            },
        ];
        let json = serde_json::to_string(&opts).expect("serializes");
        assert!(json.contains(r#"{"type":"toggle"}"#));
        assert!(json.contains(r#"{"type":"effort","values":["off","low","max"]}"#));
        // The absent `max` bound is skipped, not serialized as null.
        assert!(json.contains(r#"{"type":"budget_tokens","min":1024}"#));
        let back: Vec<ReasoningOption> = serde_json::from_str(&json).expect("deserializes");
        assert_eq!(back, opts);
    }

    #[test]
    fn pre_versioned_cache_is_rejected() {
        // A cache written before schema versioning omits the field, so it
        // deserializes to `0`, which never equals the current version.
        // `load_active_catalog` treats that as an incompatible cache and
        // falls back to the bundled seed.
        let json = r#"{"updated_at":0,"source":"old","models":[]}"#;
        let cat: Catalog = serde_json::from_str(json).expect("parses");
        assert_eq!(cat.schema_version, 0);
        assert_ne!(cat.schema_version, CATALOG_SCHEMA_VERSION);
    }

    #[test]
    fn validate_thinking_level_rejects_out_of_vocabulary() {
        // Adaptive Anthropic model: the advertised effort enum plus the
        // always-available off, and nothing else.
        let mut adaptive = sample_model("anthropic", "claude-opus-4-7");
        adaptive.reasoning = true;
        adaptive.reasoning_options = vec![ReasoningOption::Effort {
            values: vec![
                ThinkingLevel::Low,
                ThinkingLevel::Medium,
                ThinkingLevel::High,
            ],
        }];
        assert!(validate_thinking_level(&adaptive, &ThinkingLevel::Off).is_ok());
        assert!(validate_thinking_level(&adaptive, &ThinkingLevel::High).is_ok());
        assert!(validate_thinking_level(&adaptive, &ThinkingLevel::Minimal).is_err());
        // Outside the advertised enum, even though `max` is a valid rung
        // for other models.
        assert!(validate_thinking_level(&adaptive, &ThinkingLevel::Max).is_err());

        // Legacy budget-based Anthropic model accepts every level (each
        // maps to a token budget).
        let mut budget = sample_model("anthropic", "claude-sonnet-4-5");
        budget.reasoning = true;
        budget.reasoning_options = vec![ReasoningOption::BudgetTokens {
            min: Some(1024),
            max: None,
        }];
        assert!(validate_thinking_level(&budget, &ThinkingLevel::Minimal).is_ok());
        assert!(validate_thinking_level(&budget, &ThinkingLevel::Max).is_ok());

        // OpenAI model whose effort enum excludes off: off is rejected,
        // and so is any rung the enum doesn't list.
        let mut openai = sample_model("openai", "gpt-5-pro");
        openai.api = "openai-responses".into();
        openai.reasoning = true;
        openai.reasoning_options = vec![ReasoningOption::Effort {
            values: vec![ThinkingLevel::High],
        }];
        assert!(validate_thinking_level(&openai, &ThinkingLevel::High).is_ok());
        assert!(validate_thinking_level(&openai, &ThinkingLevel::Off).is_err());
        assert!(validate_thinking_level(&openai, &ThinkingLevel::Medium).is_err());

        // Non-reasoning model offers only off; any effort is an error.
        let plain = sample_model("openai", "gpt-4o");
        assert!(validate_thinking_level(&plain, &ThinkingLevel::Off).is_ok());
        assert!(validate_thinking_level(&plain, &ThinkingLevel::Max).is_err());
    }

    #[test]
    fn supported_thinking_levels_by_category() {
        // Non-reasoning: off only.
        let plain = sample_model("openai", "gpt-4o");
        assert_eq!(supported_thinking_levels(&plain), vec![ThinkingLevel::Off]);

        // OpenAI effort enum with off, returned in canonical order.
        let mut gpt = sample_model("openai", "gpt-5.5");
        gpt.api = "openai-responses".into();
        gpt.reasoning = true;
        gpt.reasoning_options = vec![ReasoningOption::Effort {
            values: vec![
                ThinkingLevel::Off,
                ThinkingLevel::Low,
                ThinkingLevel::Medium,
                ThinkingLevel::High,
                ThinkingLevel::XHigh,
            ],
        }];
        assert_eq!(
            supported_thinking_levels(&gpt),
            vec![
                ThinkingLevel::Off,
                ThinkingLevel::Low,
                ThinkingLevel::Medium,
                ThinkingLevel::High,
                ThinkingLevel::XHigh,
            ]
        );

        // Anthropic adaptive: off is added even though the effort enum
        // omits it, and the extra budget control is ignored.
        let mut opus = sample_model("anthropic", "claude-opus-4-5");
        opus.reasoning = true;
        opus.reasoning_options = vec![
            ReasoningOption::Effort {
                values: vec![
                    ThinkingLevel::Low,
                    ThinkingLevel::Medium,
                    ThinkingLevel::High,
                ],
            },
            ReasoningOption::BudgetTokens {
                min: Some(1024),
                max: None,
            },
        ];
        assert_eq!(
            supported_thinking_levels(&opus),
            vec![
                ThinkingLevel::Off,
                ThinkingLevel::Low,
                ThinkingLevel::Medium,
                ThinkingLevel::High,
            ]
        );

        // Budget-only and under-described both fall back to the full ladder.
        let mut haiku = sample_model("anthropic", "claude-haiku-4-5");
        haiku.reasoning = true;
        haiku.reasoning_options = vec![ReasoningOption::BudgetTokens {
            min: Some(1024),
            max: None,
        }];
        assert_eq!(
            supported_thinking_levels(&haiku),
            ALL_THINKING_LEVELS.to_vec()
        );

        let mut unknown = sample_model("openai", "mystery");
        unknown.api = "openai-responses".into();
        unknown.reasoning = true;
        assert_eq!(
            supported_thinking_levels(&unknown),
            ALL_THINKING_LEVELS.to_vec()
        );

        // A non-Anthropic reasoning model whose only control is a toggle
        // has no effort vocabulary, so it also gets the full ladder
        // (never just `[off]`, which would make reasoning unreachable).
        let mut toggle = sample_model("openai", "toggle-only");
        toggle.api = "openai-responses".into();
        toggle.reasoning = true;
        toggle.reasoning_options = vec![ReasoningOption::Toggle];
        assert_eq!(
            supported_thinking_levels(&toggle),
            ALL_THINKING_LEVELS.to_vec()
        );
    }

    #[test]
    fn models_are_equal_identity_not_state() {
        let mut a = sample_model("anthropic", "claude-x");
        let mut b = sample_model("anthropic", "claude-x");
        // State diverges, identity doesn't.
        a.cost.input = 100.0;
        b.context_window = 1;
        assert!(models_are_equal(&a, &b));
        b.id = "claude-y".into();
        assert!(!models_are_equal(&a, &b));
    }

    /// The bundled seed and overrides are part of the binary; if either
    /// fails to parse the registry won't load. Regression-test that the
    /// committed JSON stays well-formed.
    #[test]
    fn bundled_seed_and_overrides_parse() {
        let seed: Catalog = serde_json::from_str(SEED_MODELS_JSON).expect("seed parses");
        let overrides: OverridesFile =
            serde_json::from_str(OVERRIDES_JSON).expect("overrides parse");
        // Seed must contain at least one Anthropic and one OpenAI model.
        assert!(seed.models.iter().any(|m| m.provider == "anthropic"));
        assert!(seed.models.iter().any(|m| m.provider == "openai"));
        // All seed entries must be on the two filtered providers.
        for m in &seed.models {
            assert!(
                m.provider == "anthropic" || m.provider == "openai",
                "unexpected provider {} in seed",
                m.provider
            );
        }
        // Every override target must reference a real seed entry
        // before we try to apply it. This catches typos at test time.
        for entry in &overrides.overrides {
            assert!(
                seed.models
                    .iter()
                    .any(|m| m.provider == entry.target.provider && m.id == entry.target.id),
                "override target {}/{} does not match any seed entry",
                entry.target.provider,
                entry.target.id
            );
        }
    }

    /// The bundled seed's reasoning controls drive the adaptive
    /// derivation: opus-4-5 advertises an effort control, so it derives
    /// adaptive on, while a budget-only model does not. Built from the
    /// seed directly (not [`ModelRegistry::load`]) so the assertion
    /// doesn't depend on an ambient `~/.aj/models.json`.
    #[test]
    fn seed_derives_adaptive_from_effort_controls() {
        let seed: Catalog = serde_json::from_str(SEED_MODELS_JSON).expect("seed parses");
        let reg = ModelRegistry::from_catalog_with_overrides(seed, bundled_overrides(), "seed");
        let opus = reg
            .get("anthropic", "claude-opus-4-5")
            .expect("opus-4-5 present in seed");
        assert!(
            supports_adaptive_thinking(opus),
            "opus-4-5 advertises an effort control, so it derives adaptive"
        );
        let sonnet = reg
            .get("anthropic", "claude-sonnet-4-5")
            .expect("sonnet-4-5 present in seed");
        assert!(
            !supports_adaptive_thinking(sonnet),
            "sonnet-4-5 is budget-only, so it does not derive adaptive"
        );
        // Adaptive thinking is Anthropic-only; an OpenAI model never derives it.
        if let Some(m) = reg.get("openai", "gpt-5.2") {
            assert!(!supports_adaptive_thinking(m));
        }
    }

    /// The bundled Codex seed must parse and every entry must carry
    /// the expected provider id / api / base url. Misconfigured seed
    /// entries would silently hide Codex models from the picker, so
    /// pin the invariants here.
    #[test]
    fn bundled_codex_seed_well_formed() {
        let seed = bundled_codex_seed();
        assert!(!seed.is_empty(), "codex seed must be non-empty");

        // every codex entry shares the same fixed
        // provider/api/base_url triple.
        for m in &seed {
            assert_eq!(m.provider, CODEX_PROVIDER_ID);
            assert_eq!(m.api, "openai-codex-responses");
            assert_eq!(m.base_url, "https://chatgpt.com/backend-api");
            // max_tokens hard-coded at 128_000 across the
            // entire codex set.
            assert_eq!(m.max_tokens, 128_000);
        }

        // calls out the canonical id list; spot-check the
        // headline entries.
        let ids: std::collections::HashSet<&str> = seed.iter().map(|m| m.id.as_str()).collect();
        for expected in [
            "gpt-5.2",
            "gpt-5.5",
            "gpt-5.6-sol",
            "gpt-5.6-terra",
            "gpt-5.6-luna",
        ] {
            assert!(ids.contains(expected), "codex seed missing {expected}");
        }
        // gpt-5.4 and gpt-5.4-mini are hidden in the Codex picker, so they
        // are intentionally absent from the seed.
        assert!(!ids.contains("gpt-5.4"), "gpt-5.4 must stay dropped");
        assert!(
            !ids.contains("gpt-5.4-mini"),
            "gpt-5.4-mini must stay dropped"
        );

        // Context windows are unified at 400k, the real gpt-5 window. The
        // Codex client itself reports a lower 272k figure, but that's an
        // artificial cost/compaction cap, not the model's true capacity.
        for m in &seed {
            assert_eq!(
                m.context_window, 400_000,
                "unexpected context_window for {}",
                m.id
            );
        }

        // The gpt-5.5 and gpt-5.6 families carry a context tier that fires
        // above 272k input tokens, reachable within the 400k window.
        // gpt-5.2 is flat-rate with no tier.
        for m in &seed {
            match m.id.as_str() {
                "gpt-5.5" | "gpt-5.6-sol" | "gpt-5.6-terra" | "gpt-5.6-luna" => {
                    assert_eq!(
                        m.cost.tiers.len(),
                        1,
                        "{} must have exactly one context tier",
                        m.id
                    );
                    assert_eq!(
                        m.cost.tiers[0].input_tokens_above, 272_000,
                        "{} tier threshold",
                        m.id
                    );
                }
                _ => assert!(m.cost.tiers.is_empty(), "{} must have no tiers", m.id),
            }
        }
    }

    /// `splice_codex_seed` must be additive only: entries already in
    /// the model list win over the seed so refreshed user caches
    /// aren't silently rewritten by the in-process seed.
    #[test]
    fn splice_codex_seed_is_additive_only() {
        let mut models = vec![ModelInfo {
            id: "gpt-5.5".into(),
            name: "gpt-5.5 (from cache)".into(),
            api: "openai-codex-responses".into(),
            provider: CODEX_PROVIDER_ID.into(),
            base_url: "https://chatgpt.com/backend-api".into(),
            reasoning: true,
            reasoning_options: Vec::new(),
            supports_verbosity: false,
            input: vec![InputModality::Text, InputModality::Image],
            cost: ModelCost {
                input: 9.99,
                output: 9.99,
                cache_read: 9.99,
                cache_write: 9.99,
                tiers: Vec::new(),
            },
            context_window: 272_000,
            max_tokens: 128_000,
        }];

        let seed = bundled_codex_seed();
        let total_seed = seed.len();
        let appended = splice_codex_seed(&mut models, seed);

        // The seed entry for gpt-5.5 should not have been re-applied.
        assert_eq!(appended, total_seed - 1);
        assert_eq!(models.len(), total_seed);

        // The pre-existing entry's cost is preserved.
        let gpt55 = models
            .iter()
            .find(|m| m.id == "gpt-5.5")
            .expect("gpt-5.5 present");
        assert_eq!(gpt55.name, "gpt-5.5 (from cache)");
        assert!((gpt55.cost.input - 9.99).abs() < 1e-9);

        // A second splice with the same seed appends nothing.
        let appended_again = splice_codex_seed(&mut models, bundled_codex_seed());
        assert_eq!(appended_again, 0);
    }

    /// Non-codex entries in `codex.json` would be a maintainer
    /// mistake; the loader filters them out rather than letting them
    /// inject a foreign provider into the registry.
    #[test]
    fn splice_skips_non_codex_entries() {
        let stray = ModelInfo {
            id: "claude-zoo".into(),
            name: "Claude Zoo".into(),
            api: "anthropic-messages".into(),
            provider: "anthropic".into(),
            base_url: "https://api.anthropic.com".into(),
            reasoning: false,
            reasoning_options: Vec::new(),
            supports_verbosity: false,
            input: vec![InputModality::Text],
            cost: ModelCost::default(),
            context_window: 1,
            max_tokens: 1,
        };
        let mut models = Vec::new();
        let appended = splice_codex_seed(&mut models, vec![stray]);
        // The splice accepts whatever the caller passes — filtering of
        // non-codex entries happens inside `bundled_codex_seed` before
        // the splice runs, not in the splice itself. Pin the splice's
        // behavior here so it doesn't grow surprising filters later.
        assert_eq!(appended, 1);
        assert_eq!(models.len(), 1);
    }

    /// `ModelRegistry::load()` must surface the Codex models, even
    /// when the bundled `models.json` snapshot predates the codex
    /// seed.
    #[test]
    fn load_surfaces_codex_models() {
        let reg = ModelRegistry::load();
        assert!(reg.providers().contains(&"openai-codex"));
        let codex = reg.models("openai-codex");
        assert!(!codex.is_empty());

        // gpt-5.5 is the canonical xhigh-capable, top-tier codex model.
        let gpt55 = reg
            .get("openai-codex", "gpt-5.5")
            .expect("gpt-5.5 present after load");
        assert!(gpt55.reasoning);
        assert!(!supports_adaptive_thinking(gpt55));
        // Codex carries a hand-curated effort vocabulary (low..xhigh),
        // with no `off` rung since the backend can't disable reasoning.
        assert_eq!(
            gpt55.reasoning_options,
            vec![ReasoningOption::Effort {
                values: vec![
                    ThinkingLevel::Low,
                    ThinkingLevel::Medium,
                    ThinkingLevel::High,
                    ThinkingLevel::XHigh,
                ],
            }]
        );
        assert_eq!(gpt55.api, "openai-codex-responses");
        assert_eq!(gpt55.base_url, "https://chatgpt.com/backend-api");
        assert_eq!(gpt55.context_window, 400_000);
        assert_eq!(gpt55.max_tokens, 128_000);
    }
}
