//! Model metadata, registry, and catalog loading.
//!
//! Defines the static catalog of known models and the lookup surface used
//! by the rest of the codebase. The registry has no runtime network
//! dependency: it is populated at startup from a JSON catalog, either the
//! bundled seed compiled into the binary via `include_str!` or an
//! optional user cache at `~/.aj/models.json` written by the catalog
//! refresh CLI. Overrides from the bundled `overrides.json` are applied
//! on top of whichever catalog loads, so authored corrections survive
//! refreshes.

use std::collections::HashMap;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::types::{ThinkingLevel, Usage};

/// Bundled seed, generated by the catalog refresh process. Always
/// present; guarantees the registry loads on first run, offline, or when
/// models.dev is unreachable. Updated by running the refresh command and
/// committing the resulting JSON.
const SEED_MODELS_JSON: &str = include_str!("../data/models.json");

/// Bundled overrides. Corrects known upstream inaccuracies and supplies
/// fields models.dev does not carry
/// (`supports_adaptive_thinking`). Applied on every load — seed and user
/// cache alike.
const OVERRIDES_JSON: &str = include_str!("../data/overrides.json");

/// Bundled OpenAI Codex seed. The `openai-codex` provider points at
/// the ChatGPT subscription backend (`chatgpt.com/backend-api`) and
/// is not enumerated by models.dev, so its model list is maintained
/// here alongside the overrides file. The list is
/// authoritative: refresh appends these entries to every fresh cache
/// (defensively filtering any upstream re-emission first), and load
/// splices them in so users on a stale cache or an older bundled seed
/// still see Codex models. `context_window` is set to `272000` (the
/// observed server cap, not the marketing number) and `max_tokens`
/// to `128000`; pricing is hand-curated.
const CODEX_SEED_JSON: &str = include_str!("../data/codex.json");

/// Provider id used to key Codex catalog entries. Exposed so the
/// refresh and load paths agree on the value used for filtering and
/// splicing.
pub const CODEX_PROVIDER_ID: &str = "openai-codex";

/// Maximum allowed catalog age before the registry warns the user.
/// 90 days is a compromise — pricing changes on the order of months and
/// new models ship every few weeks; tighter thresholds would warn too
/// often on stable catalogs.
const STALENESS_THRESHOLD_DAYS: i64 = 90;

// ============================================================================
// Model Metadata
// ============================================================================

/// Supported input modality. Matches the lowercase string form used by
/// the catalog JSON ("text" / "image").
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum InputModality {
    Text,
    Image,
}

/// Per-million-token cost rates for a model.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct ModelCost {
    pub input: f64,
    pub output: f64,
    pub cache_read: f64,
    pub cache_write: f64,
    /// Context-based pricing tiers. Empty for flat-rate models.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tiers: Vec<ModelCostTier>,
}

/// A context-based pricing tier: a step function that replaces the base
/// [`ModelCost`] rates for the whole request once the request is large
/// enough. Tiers are not marginal, the selected tier's rates apply to
/// every token category of the entire request.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct ModelCostTier {
    /// Total input-side token threshold for this tier, compared against
    /// `input + cache_read + cache_write` of the request's usage. The
    /// tier applies when the total input-side usage is strictly greater
    /// than this value. Among all tiers that apply, the one with the
    /// largest `input_tokens_above` wins and its rates replace the base
    /// rates for the whole request. If two tiers share a threshold the
    /// later one in the list wins, but well-formed data has no such ties.
    pub input_tokens_above: u64,
    pub input: f64,
    pub output: f64,
    pub cache_read: f64,
    pub cache_write: f64,
}

/// Static metadata for a known model. Each entry is the result of
/// merging a catalog entry with any matching overrides.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ModelInfo {
    /// Model identifier sent to the API (e.g. "claude-sonnet-4-20250514").
    pub id: String,
    /// Human-readable name (e.g. "Claude Sonnet 4").
    pub name: String,
    /// API type. One of "anthropic-messages", "openai-completions", or
    /// "openai-responses". Each `(provider, id)` pair has exactly one
    /// `api` — there is no duplication.
    pub api: String,
    /// Provider name (e.g. "anthropic", "openai").
    pub provider: String,
    /// Base URL for API requests.
    pub base_url: String,
    /// Whether the model supports extended thinking / reasoning.
    pub reasoning: bool,
    /// Whether the model uses Anthropic's adaptive thinking API
    /// (`thinking: {type: "adaptive"}` + `output_config: {effort: ...}`)
    /// instead of the older budget-based thinking. Also governs whether
    /// the `interleaved-thinking-2025-05-14` beta header is sent —
    /// adaptive models have interleaved thinking built in and either
    /// reject or ignore the header.
    ///
    /// Defaults to `true` for Anthropic reasoning models so a new model
    /// absent from the overrides uses the modern API rather than
    /// silently falling back to budget-based thinking; legacy
    /// budget-only models are pinned `false` via overrides. Always
    /// `false` for non-Anthropic and non-reasoning models. The serde
    /// default is `false` (belt-and-suspenders for hand-written
    /// fixtures); the catalog writes the value explicitly.
    #[serde(default)]
    pub supports_adaptive_thinking: bool,
    /// Whether the model honours OpenAI's `text.verbosity` parameter
    /// (the answer-length knob, see [`crate::types::Verbosity`]). The
    /// gpt-5 family on the Responses / Codex wire supports it; older
    /// OpenAI models and non-OpenAI models do not. Gates whether a
    /// caller-set verbosity reaches the request: unsupported models
    /// silently ignore the knob rather than 400.
    ///
    /// Not in models.dev. Derived in the refresh mapper (the OpenAI
    /// gpt-5 family on `openai-responses`, and OpenRouter's
    /// `supported_parameters`), hand-set on the Codex seed, and
    /// pinnable per model via overrides. The serde default is `false`.
    #[serde(default)]
    pub supports_verbosity: bool,
    /// Supported input modalities.
    pub input: Vec<InputModality>,
    /// Pricing per million tokens.
    pub cost: ModelCost,
    /// Maximum context window in tokens.
    pub context_window: u64,
    /// Maximum output tokens.
    pub max_tokens: u64,
    /// Optional extra HTTP headers the client should send (e.g. for
    /// providers like Copilot/Kimi that require static identity headers).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<HashMap<String, String>>,
}

// ============================================================================
// Catalog file schema
// ============================================================================

/// On-disk catalog format shared by the bundled seed and the user cache.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Catalog {
    /// Unix milliseconds when the catalog was last refreshed. Drives the
    /// staleness warning.
    pub updated_at: i64,
    /// Origin label (e.g. "models.dev"). Free-form; informational.
    pub source: String,
    pub models: Vec<ModelInfo>,
}

// ============================================================================
// Overrides file schema
// ============================================================================

/// On-disk overrides file. Each entry targets one `(provider, id)` pair
/// and shallow-merges the patch fields onto the matched model.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct OverridesFile {
    pub overrides: Vec<OverrideEntry>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct OverrideEntry {
    pub target: OverrideTarget,
    pub patch: OverridePatch,
    /// Required free-form rationale; surfaces to anyone reviewing the
    /// overrides file later.
    pub reason: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct OverrideTarget {
    pub provider: String,
    pub id: String,
}

/// Shallow-merge patch over a [`ModelInfo`]. Each `Option` is leave-alone
/// when `None` and replace-whole when `Some`. Nested objects (`cost`,
/// `input`) are replaced wholesale, not deep-merged — predictable wins
/// over clever.
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct OverridePatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supports_adaptive_thinking: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supports_verbosity: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input: Option<Vec<InputModality>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost: Option<ModelCost>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context_window: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<HashMap<String, String>>,
}

// ============================================================================
// Registry
// ============================================================================

/// In-memory registry of all known models, organized by provider.
///
/// Built from a [`Catalog`] (seed or user cache) plus an
/// [`OverridesFile`]. Lookups are O(1) by `(provider, id)`; listing
/// preserves catalog order so output is stable.
#[derive(Clone, Debug)]
pub struct ModelRegistry {
    /// `provider -> id -> ModelInfo`, for O(1) lookups.
    by_provider: HashMap<String, HashMap<String, ModelInfo>>,
    /// First-seen provider order, for deterministic listing.
    provider_order: Vec<String>,
    /// First-seen model id order per provider, for deterministic listing.
    model_order: HashMap<String, Vec<String>>,
    /// Free-form label describing where the active catalog came from
    /// (e.g. "bundled seed", "user cache <path>"). Surfaced only in
    /// diagnostic output.
    source_label: String,
    /// `updated_at` from the catalog, retained for staleness logic and
    /// inspection.
    pub updated_at: i64,
}

impl ModelRegistry {
    /// Load the registry from the canonical sources, in priority order:
    ///
    /// 1. User cache at `~/.aj/models.json` if present and parseable.
    /// 2. Bundled seed at `data/models.json` (always available).
    ///
    /// Overrides from the bundled `data/overrides.json` are applied on
    /// top of the chosen catalog. Emits a one-line warning via `tracing`
    /// when the active catalog is older than [`STALENESS_THRESHOLD_DAYS`].
    pub fn load() -> Self {
        let (catalog, source) = load_active_catalog();
        let overrides = bundled_overrides();
        Self::from_catalog_with_overrides(catalog, overrides, source)
    }

    /// Build a registry from a known catalog + overrides set. Useful for
    /// tests and for callers that have already obtained their data
    /// out-of-band.
    pub fn from_catalog_with_overrides(
        catalog: Catalog,
        overrides: OverridesFile,
        source_label: impl Into<String>,
    ) -> Self {
        let mut models = catalog.models;
        // Splice in the Codex seed before overrides run so authored
        // patches can target Codex models too. Entries already present
        // in the catalog (e.g. a freshly-refreshed user cache that
        // included them) are not duplicated; the splice is purely
        // additive for `(provider, id)` keys that aren't there yet.
        splice_codex_seed(&mut models, bundled_codex_seed());
        // Apply overrides in declared order. Each entry shallow-merges
        // its patch onto the first matching `(provider, id)`.
        for entry in &overrides.overrides {
            apply_override(&mut models, entry);
        }

        let mut by_provider: HashMap<String, HashMap<String, ModelInfo>> = HashMap::new();
        let mut provider_order: Vec<String> = Vec::new();
        let mut model_order: HashMap<String, Vec<String>> = HashMap::new();

        for model in models {
            if !by_provider.contains_key(&model.provider) {
                provider_order.push(model.provider.clone());
                model_order.insert(model.provider.clone(), Vec::new());
            }
            let provider_map = by_provider.entry(model.provider.clone()).or_default();
            if !provider_map.contains_key(&model.id) {
                model_order
                    .get_mut(&model.provider)
                    .expect("inserted above")
                    .push(model.id.clone());
            }
            // Last write wins on duplicate `(provider, id)` — overrides
            // and catalogs alike rely on uniqueness, but this keeps the
            // registry deterministic if a stray duplicate slips through.
            provider_map.insert(model.id.clone(), model);
        }

        let registry = Self {
            by_provider,
            provider_order,
            model_order,
            source_label: source_label.into(),
            updated_at: catalog.updated_at,
        };
        registry.maybe_warn_stale();
        registry
    }

    /// Emit a `tracing::warn!` if the active catalog is older than the
    /// staleness threshold. Skipped silently for `updated_at <= 0` so
    /// callers can suppress the warning by zeroing the field (used in
    /// tests).
    fn maybe_warn_stale(&self) {
        if self.updated_at <= 0 {
            return;
        }
        let now_ms = chrono::Utc::now().timestamp_millis();
        let age_ms = now_ms.saturating_sub(self.updated_at);
        let age_days = age_ms / (1000 * 60 * 60 * 24);
        if age_days > STALENESS_THRESHOLD_DAYS {
            tracing::warn!(
                "model catalog ({}) is {} days old; run `aj update-models` to refresh",
                self.source_label,
                age_days
            );
        }
    }

    /// Look up a model by `(provider, id)`. Returns `None` if either is
    /// unknown.
    pub fn get(&self, provider: &str, model_id: &str) -> Option<&ModelInfo> {
        self.by_provider.get(provider).and_then(|m| m.get(model_id))
    }

    /// List all known providers in stable insertion order.
    pub fn providers(&self) -> Vec<&str> {
        self.provider_order.iter().map(String::as_str).collect()
    }

    /// List all known models for a provider in stable insertion order.
    /// Returns an empty vec for unknown providers.
    pub fn models(&self, provider: &str) -> Vec<&ModelInfo> {
        let Some(ids) = self.model_order.get(provider) else {
            return Vec::new();
        };
        let Some(map) = self.by_provider.get(provider) else {
            return Vec::new();
        };
        ids.iter().filter_map(|id| map.get(id)).collect()
    }

    /// Diagnostic label describing the active catalog source. Useful
    /// in error messages and CLI output.
    pub fn source_label(&self) -> &str {
        &self.source_label
    }
}

// ============================================================================
// Cost Calculation
// ============================================================================

/// Compute dollar costs per token category and the running total, and
/// store them in `usage.cost`. Rates in `cost` are
/// dollars-per-million-tokens; the function divides through by 1e6.
///
/// When `cost` carries context-based tiers, the rate set is chosen up
/// front: the total input-side usage (`input + cache_read +
/// cache_write`) selects the highest tier whose `input_tokens_above` it
/// strictly exceeds, and that tier's rates replace the base rates for
/// every token category. With no matching tier the base rates apply.
/// The selected rates are applied to the usage tokens exactly once, so
/// the per-category math does not branch on whether a tier was chosen.
//
// `u64 → f64` is exact for any value below 2^53; token counts stay
// safely below that ceiling, so the `as` cast loses no precision in
// practice. There's no stable safe converter for this direction in
// std.
#[allow(clippy::as_conversions)]
pub fn calculate_cost(cost: &ModelCost, usage: &mut Usage) {
    const PER_MILLION: f64 = 1_000_000.0;

    let input_side = usage.input + usage.cache_read + usage.cache_write;
    let rates = cost
        .tiers
        .iter()
        .filter(|tier| tier.input_tokens_above < input_side)
        .max_by_key(|tier| tier.input_tokens_above)
        .map_or(
            (cost.input, cost.output, cost.cache_read, cost.cache_write),
            |tier| (tier.input, tier.output, tier.cache_read, tier.cache_write),
        );
    let (input_rate, output_rate, cache_read_rate, cache_write_rate) = rates;

    usage.cost.input = (input_rate / PER_MILLION) * usage.input as f64;
    usage.cost.output = (output_rate / PER_MILLION) * usage.output as f64;
    usage.cost.cache_read = (cache_read_rate / PER_MILLION) * usage.cache_read as f64;
    usage.cost.cache_write = (cache_write_rate / PER_MILLION) * usage.cache_write as f64;
    usage.cost.total =
        usage.cost.input + usage.cost.output + usage.cost.cache_read + usage.cost.cache_write;
}

// ============================================================================
// Capability Probes
// ============================================================================

/// Structural equality of two models by `(provider, api, id)`. Two
/// `ModelInfo`s with identical identity but different metadata still
/// compare equal — identity, not state, is what cross-provider replay
/// cares about.
pub fn models_are_equal(a: &ModelInfo, b: &ModelInfo) -> bool {
    a.provider == b.provider && a.api == b.api && a.id == b.id
}

/// Whether the model uses Anthropic's adaptive thinking API. Thin
/// accessor over [`ModelInfo::supports_adaptive_thinking`].
pub fn supports_adaptive_thinking(model: &ModelInfo) -> bool {
    model.supports_adaptive_thinking
}

/// Whether the model honours OpenAI's `text.verbosity` parameter.
/// Thin accessor over [`ModelInfo::supports_verbosity`].
pub fn supports_verbosity(model: &ModelInfo) -> bool {
    model.supports_verbosity
}

/// Validate a requested [`ThinkingLevel`] against a model's wire
/// vocabulary, returning a human-readable message when the level can't
/// be honoured.
///
/// aj sends the chosen effort verbatim — there is no remapping or
/// silent downgrade — so a level the provider's effort vocabulary
/// lacks is rejected here before the request is built:
///
/// - Anthropic adaptive models take an `effort` enum with no `minimal`
///   rung, so `Minimal` is rejected. Legacy budget-based Anthropic
///   models translate every level to a token budget and accept the
///   rest.
/// - The OpenAI-family APIs (Responses, Chat Completions, Codex) accept
///   the full `minimal`..`max` range.
///
/// Per-model effort support *within* a provider's vocabulary (e.g.
/// which adaptive Anthropic model accepts `max` vs `xhigh`, or which
/// OpenAI model exposes `max`) is deliberately not modelled
/// here: those requests are sent through and the provider API returns
/// its own 400.
///
/// Non-reasoning models ignore the level entirely (the providers omit
/// the thinking parameter), so any level is accepted as a no-op.
pub fn validate_thinking_level(model: &ModelInfo, level: &ThinkingLevel) -> Result<(), String> {
    if !model.reasoning {
        return Ok(());
    }
    match model.api.as_str() {
        "anthropic-messages" => {
            if model.supports_adaptive_thinking && matches!(level, ThinkingLevel::Minimal) {
                return Err(format!(
                    "model '{}' does not support thinking level 'minimal'; \
                     supported: low, medium, high, xhigh, max",
                    model.id
                ));
            }
            Ok(())
        }
        _ => Ok(()),
    }
}

// ============================================================================
// Catalog loading internals
// ============================================================================

/// Pick the active catalog, in priority order:
///
/// 1. User cache at `~/.aj/models.json` if present and parseable.
/// 2. Bundled seed (always succeeds — a malformed seed is a build-time
///    bug we surface via panic).
///
/// A user cache that exists but fails to parse logs a warning and falls
/// through to the seed. A missing cache falls through silently.
fn load_active_catalog() -> (Catalog, String) {
    if let Some(path) = user_cache_path()
        && path.exists()
    {
        match std::fs::read_to_string(&path) {
            Ok(body) => match serde_json::from_str::<Catalog>(&body) {
                Ok(cat) => return (cat, format!("user cache {}", path.display())),
                Err(err) => tracing::warn!(
                    "failed to parse user catalog at {}: {err}; falling back to bundled seed",
                    path.display()
                ),
            },
            Err(err) => tracing::warn!(
                "failed to read user catalog at {}: {err}; falling back to bundled seed",
                path.display()
            ),
        }
    }

    let seed: Catalog = serde_json::from_str(SEED_MODELS_JSON)
        .expect("bundled models.json must be valid; check src/aj-models/data/models.json");
    (seed, "bundled seed".to_string())
}

/// Parse the bundled overrides. Failure here is non-fatal: we log a
/// warning and proceed with no overrides, so a malformed file at most
/// degrades cost/capability accuracy without bricking the registry.
pub fn bundled_overrides() -> OverridesFile {
    serde_json::from_str(OVERRIDES_JSON).unwrap_or_else(|err| {
        tracing::warn!("failed to parse bundled overrides.json: {err}; ignoring");
        OverridesFile { overrides: vec![] }
    })
}

/// On-disk shape of the bundled Codex seed file. Lives in its own
/// struct so the catalog and seed files don't share the
/// `updated_at`/`source` framing — the Codex list has no upstream and
/// no refresh timestamp.
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct CodexSeedFile {
    pub models: Vec<ModelInfo>,
}

/// Parse the bundled OpenAI Codex seed (`data/codex.json`). Failure
/// here is non-fatal: we log a warning and proceed with an empty list,
/// so a malformed file at most hides Codex models without bricking the
/// registry. Each entry must already carry
/// `provider == CODEX_PROVIDER_ID`; non-Codex entries are dropped with
/// a warning so the file can't accidentally inject other providers.
pub fn bundled_codex_seed() -> Vec<ModelInfo> {
    let parsed: CodexSeedFile = match serde_json::from_str(CODEX_SEED_JSON) {
        Ok(file) => file,
        Err(err) => {
            tracing::warn!("failed to parse bundled codex.json: {err}; ignoring");
            return Vec::new();
        }
    };
    parsed
        .models
        .into_iter()
        .filter(|m| {
            if m.provider == CODEX_PROVIDER_ID {
                true
            } else {
                tracing::warn!(
                    "codex.json entry {}/{} has unexpected provider; dropping",
                    m.provider,
                    m.id
                );
                false
            }
        })
        .collect()
}

/// Splice the Codex seed onto an existing model list, adding entries
/// for `(provider, id)` keys not already present and leaving existing
/// entries untouched. The catalog's prior contents win on conflict so
/// a user cache that already carries refreshed Codex models doesn't
/// have its values silently rewritten by the in-process seed.
///
/// Returns the number of entries appended; useful in diagnostics and
/// tests.
pub fn splice_codex_seed(models: &mut Vec<ModelInfo>, seed: Vec<ModelInfo>) -> usize {
    if seed.is_empty() {
        return 0;
    }
    let existing: std::collections::HashSet<(String, String)> = models
        .iter()
        .map(|m| (m.provider.clone(), m.id.clone()))
        .collect();
    let mut appended = 0;
    for entry in seed {
        if existing.contains(&(entry.provider.clone(), entry.id.clone())) {
            continue;
        }
        models.push(entry);
        appended += 1;
    }
    appended
}

/// Resolve the user-cache path (`~/.aj/models.json`). Returns `None` if
/// the home directory cannot be determined.
pub fn user_cache_path() -> Option<PathBuf> {
    let mut p = home_dir()?;
    p.push(".aj");
    p.push("models.json");
    Some(p)
}

/// Local `home_dir` helper. `std::env::home_dir` was un-deprecated in
/// 1.86 but still carries the `deprecated` attribute on older toolchains
/// we want to build on; the `allow` keeps us compatible without pulling
/// in the `dirs` crate for one lookup.
fn home_dir() -> Option<PathBuf> {
    #[allow(deprecated)]
    {
        std::env::home_dir()
    }
}

/// Apply a single override entry to the model list, in place. Targets
/// that don't match any model log at debug — overrides for unreleased
/// or removed models are common during a transition.
pub(crate) fn apply_override(models: &mut [ModelInfo], entry: &OverrideEntry) {
    let Some(model) = models
        .iter_mut()
        .find(|m| m.provider == entry.target.provider && m.id == entry.target.id)
    else {
        tracing::debug!(
            "override target {}/{} not found in catalog (skipping); reason: {}",
            entry.target.provider,
            entry.target.id,
            entry.reason
        );
        return;
    };

    let p = &entry.patch;
    if let Some(v) = &p.name {
        model.name = v.clone();
    }
    if let Some(v) = &p.api {
        model.api = v.clone();
    }
    if let Some(v) = &p.base_url {
        model.base_url = v.clone();
    }
    if let Some(v) = p.reasoning {
        model.reasoning = v;
    }
    if let Some(v) = p.supports_adaptive_thinking {
        model.supports_adaptive_thinking = v;
    }
    if let Some(v) = p.supports_verbosity {
        model.supports_verbosity = v;
    }
    if let Some(v) = &p.input {
        model.input = v.clone();
    }
    if let Some(v) = &p.cost {
        model.cost = v.clone();
    }
    if let Some(v) = p.context_window {
        model.context_window = v;
    }
    if let Some(v) = p.max_tokens {
        model.max_tokens = v;
    }
    if let Some(v) = &p.headers {
        model.headers = Some(v.clone());
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::Usage;

    fn sample_model(provider: &str, id: &str) -> ModelInfo {
        ModelInfo {
            id: id.into(),
            name: id.into(),
            api: "anthropic-messages".into(),
            provider: provider.into(),
            base_url: "https://example.invalid".into(),
            reasoning: false,
            supports_adaptive_thinking: false,
            supports_verbosity: false,
            input: vec![InputModality::Text],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.3,
                cache_write: 3.75,
                tiers: Vec::new(),
            },
            context_window: 200_000,
            max_tokens: 64_000,
            headers: None,
        }
    }

    fn empty_overrides() -> OverridesFile {
        OverridesFile { overrides: vec![] }
    }

    #[test]
    fn registry_lookup_and_listing() {
        let cat = Catalog {
            // updated_at: 0 suppresses the staleness warning in tests.
            updated_at: 0,
            source: "test".into(),
            models: vec![
                sample_model("anthropic", "claude-x"),
                sample_model("anthropic", "claude-y"),
                sample_model("openai", "gpt-z"),
            ],
        };
        let reg = ModelRegistry::from_catalog_with_overrides(cat, empty_overrides(), "test");

        // Lookups
        assert!(reg.get("anthropic", "claude-x").is_some());
        assert!(reg.get("openai", "gpt-z").is_some());
        assert!(reg.get("openai", "gpt-missing").is_none());
        assert!(reg.get("nope", "x").is_none());

        // Stable ordering. The bundled Codex seed splice appends
        // `openai-codex` after the explicit catalog providers when
        // the catalog itself doesn't carry the Codex entries.
        assert_eq!(reg.providers(), vec!["anthropic", "openai", "openai-codex"]);
        let anthropic_ids: Vec<_> = reg
            .models("anthropic")
            .iter()
            .map(|m| m.id.as_str())
            .collect();
        assert_eq!(anthropic_ids, vec!["claude-x", "claude-y"]);
        assert!(reg.models("nope").is_empty());

        // The codex splice fed entries; the registry surfaces them
        // under the codex provider with the codex api string.
        let codex_ids: Vec<_> = reg
            .models("openai-codex")
            .iter()
            .map(|m| m.id.as_str())
            .collect();
        assert!(!codex_ids.is_empty(), "codex seed populated");
        for m in reg.models("openai-codex") {
            assert_eq!(m.api, "openai-codex-responses");
            assert_eq!(m.base_url, "https://chatgpt.com/backend-api");
        }
    }

    #[test]
    fn overrides_shallow_merge() {
        let cat = Catalog {
            updated_at: 0,
            source: "test".into(),
            models: vec![sample_model("anthropic", "claude-opus")],
        };
        let overrides = OverridesFile {
            overrides: vec![OverrideEntry {
                target: OverrideTarget {
                    provider: "anthropic".into(),
                    id: "claude-opus".into(),
                },
                patch: OverridePatch {
                    supports_adaptive_thinking: Some(true),
                    cost: Some(ModelCost {
                        input: 5.0,
                        output: 25.0,
                        cache_read: 0.5,
                        cache_write: 6.25,
                        tiers: Vec::new(),
                    }),
                    ..Default::default()
                },
                reason: "test".into(),
            }],
        };
        let reg = ModelRegistry::from_catalog_with_overrides(cat, overrides, "test");
        let m = reg.get("anthropic", "claude-opus").unwrap();
        assert!(m.supports_adaptive_thinking);
        assert_eq!(m.cost.cache_read, 0.5);
        // Untouched fields remain.
        assert_eq!(m.context_window, 200_000);
        assert_eq!(m.input, vec![InputModality::Text]);
    }

    #[test]
    fn overrides_target_unknown_is_silent() {
        let cat = Catalog {
            updated_at: 0,
            source: "test".into(),
            models: vec![sample_model("anthropic", "real-model")],
        };
        let overrides = OverridesFile {
            overrides: vec![OverrideEntry {
                target: OverrideTarget {
                    provider: "anthropic".into(),
                    id: "ghost-model".into(),
                },
                patch: OverridePatch {
                    supports_adaptive_thinking: Some(true),
                    ..Default::default()
                },
                reason: "test".into(),
            }],
        };
        // Should not panic; the matching entry is preserved.
        let reg = ModelRegistry::from_catalog_with_overrides(cat, overrides, "test");
        assert!(reg.get("anthropic", "real-model").is_some());
        assert!(reg.get("anthropic", "ghost-model").is_none());
    }

    #[test]
    fn calculate_cost_basic() {
        let model = sample_model("anthropic", "claude-x");
        let mut usage = Usage {
            input: 1_000_000,
            output: 500_000,
            cache_read: 100_000,
            cache_write: 50_000,
            total_tokens: 0,
            cost: Default::default(),
        };
        calculate_cost(&model.cost, &mut usage);
        assert!((usage.cost.input - 3.0).abs() < 1e-9);
        assert!((usage.cost.output - 7.5).abs() < 1e-9);
        assert!((usage.cost.cache_read - 0.03).abs() < 1e-9);
        assert!((usage.cost.cache_write - 0.1875).abs() < 1e-9);
        let expected_total = 3.0 + 7.5 + 0.03 + 0.1875;
        assert!((usage.cost.total - expected_total).abs() < 1e-9);
    }

    /// A `ModelCost` with one context tier at 272k. Base rates are 1/1/1/1,
    /// the tier doubles them once the input side clears the threshold.
    fn tiered_cost() -> ModelCost {
        ModelCost {
            input: 1.0,
            output: 1.0,
            cache_read: 1.0,
            cache_write: 1.0,
            tiers: vec![ModelCostTier {
                input_tokens_above: 272_000,
                input: 2.0,
                output: 2.0,
                cache_read: 2.0,
                cache_write: 2.0,
            }],
        }
    }

    #[test]
    fn calculate_cost_tier_below_threshold_uses_base() {
        // input_side = 200_000 + 0 + 0, below the 272k threshold, so base
        // rates apply to every category.
        let cost = tiered_cost();
        let mut usage = Usage {
            input: 200_000,
            output: 100_000,
            cache_read: 0,
            cache_write: 0,
            total_tokens: 0,
            cost: Default::default(),
        };
        calculate_cost(&cost, &mut usage);
        assert!((usage.cost.input - 0.2).abs() < 1e-9);
        assert!((usage.cost.output - 0.1).abs() < 1e-9);
    }

    #[test]
    fn calculate_cost_tier_above_threshold_applies_to_all_categories() {
        // input_side = 200_000 + 50_000 + 30_000 = 280_000 > 272k, so the
        // tier's 2x rates apply to input, output, and both cache figures.
        let cost = tiered_cost();
        let mut usage = Usage {
            input: 200_000,
            output: 100_000,
            cache_read: 50_000,
            cache_write: 30_000,
            total_tokens: 0,
            cost: Default::default(),
        };
        calculate_cost(&cost, &mut usage);
        assert!((usage.cost.input - 0.4).abs() < 1e-9);
        assert!((usage.cost.output - 0.2).abs() < 1e-9);
        assert!((usage.cost.cache_read - 0.1).abs() < 1e-9);
        assert!((usage.cost.cache_write - 0.06).abs() < 1e-9);
    }

    #[test]
    fn calculate_cost_tier_boundary_is_strict() {
        // input_side exactly equals input_tokens_above, so the tier does
        // not fire (strict >). Base rates apply.
        let cost = tiered_cost();
        let mut usage = Usage {
            input: 272_000,
            output: 10_000,
            cache_read: 0,
            cache_write: 0,
            total_tokens: 0,
            cost: Default::default(),
        };
        calculate_cost(&cost, &mut usage);
        assert!((usage.cost.input - 0.272).abs() < 1e-9);
        assert!((usage.cost.output - 0.01).abs() < 1e-9);
    }

    #[test]
    fn calculate_cost_highest_matching_tier_wins() {
        // Two tiers. input_side clears both, so the higher threshold (and
        // its 5x rate) wins over the lower (3x). Tier order in the vec is
        // deliberately non-monotonic to prove selection is by value, not
        // position.
        let cost = ModelCost {
            input: 1.0,
            output: 1.0,
            cache_read: 1.0,
            cache_write: 1.0,
            tiers: vec![
                ModelCostTier {
                    input_tokens_above: 400_000,
                    input: 5.0,
                    output: 5.0,
                    cache_read: 5.0,
                    cache_write: 5.0,
                },
                ModelCostTier {
                    input_tokens_above: 272_000,
                    input: 3.0,
                    output: 3.0,
                    cache_read: 3.0,
                    cache_write: 3.0,
                },
            ],
        };
        let mut usage = Usage {
            input: 500_000,
            output: 100_000,
            cache_read: 0,
            cache_write: 0,
            total_tokens: 0,
            cost: Default::default(),
        };
        calculate_cost(&cost, &mut usage);
        assert!((usage.cost.input - 2.5).abs() < 1e-9);
        assert!((usage.cost.output - 0.5).abs() < 1e-9);
    }

    #[test]
    fn model_cost_serde_omits_empty_tiers() {
        let flat = ModelCost {
            input: 1.0,
            output: 2.0,
            cache_read: 0.5,
            cache_write: 1.0,
            tiers: Vec::new(),
        };
        let json = serde_json::to_string(&flat).expect("serializes");
        assert!(
            !json.contains("tiers"),
            "empty tiers must be omitted, got: {json}"
        );

        let tiered = tiered_cost();
        let round: ModelCost =
            serde_json::from_str(&serde_json::to_string(&tiered).expect("serializes"))
                .expect("deserializes");
        assert_eq!(round, tiered);
    }

    #[test]
    fn capability_probes() {
        let mut m = sample_model("anthropic", "x");
        assert!(!supports_adaptive_thinking(&m));
        m.supports_adaptive_thinking = true;
        assert!(supports_adaptive_thinking(&m));
    }

    #[test]
    fn validate_thinking_level_rejects_out_of_vocabulary() {
        // Adaptive Anthropic model: no `minimal` rung.
        let mut adaptive = sample_model("anthropic", "claude-opus-4-7");
        adaptive.reasoning = true;
        adaptive.supports_adaptive_thinking = true;
        assert!(validate_thinking_level(&adaptive, &ThinkingLevel::Minimal).is_err());
        assert!(validate_thinking_level(&adaptive, &ThinkingLevel::Max).is_ok());
        assert!(validate_thinking_level(&adaptive, &ThinkingLevel::XHigh).is_ok());

        // Legacy budget-based Anthropic model accepts every level
        // (each maps to a token budget).
        let mut budget = sample_model("anthropic", "claude-sonnet-4-5");
        budget.reasoning = true;
        budget.supports_adaptive_thinking = false;
        assert!(validate_thinking_level(&budget, &ThinkingLevel::Minimal).is_ok());
        assert!(validate_thinking_level(&budget, &ThinkingLevel::Max).is_ok());

        // OpenAI-family model: accepts the full minimal..max range.
        let mut openai = sample_model("openai", "gpt-5.6-sol");
        openai.api = "openai-responses".into();
        openai.reasoning = true;
        assert!(validate_thinking_level(&openai, &ThinkingLevel::Minimal).is_ok());
        assert!(validate_thinking_level(&openai, &ThinkingLevel::XHigh).is_ok());
        assert!(validate_thinking_level(&openai, &ThinkingLevel::Max).is_ok());

        // Non-reasoning model ignores the level entirely.
        let plain = sample_model("openai", "gpt-4o");
        assert!(validate_thinking_level(&plain, &ThinkingLevel::Max).is_ok());
    }

    #[test]
    fn models_are_equal_identity_not_state() {
        let mut a = sample_model("anthropic", "claude-x");
        let mut b = sample_model("anthropic", "claude-x");
        // State diverges, identity doesn't.
        a.cost.input = 100.0;
        b.context_window = 1;
        assert!(models_are_equal(&a, &b));
        b.id = "claude-y".into();
        assert!(!models_are_equal(&a, &b));
    }

    /// The bundled seed and overrides are part of the binary; if either
    /// fails to parse the registry won't load. Regression-test that the
    /// committed JSON stays well-formed.
    #[test]
    fn bundled_seed_and_overrides_parse() {
        let seed: Catalog = serde_json::from_str(SEED_MODELS_JSON).expect("seed parses");
        let overrides: OverridesFile =
            serde_json::from_str(OVERRIDES_JSON).expect("overrides parse");
        // Seed must contain at least one Anthropic and one OpenAI model.
        assert!(seed.models.iter().any(|m| m.provider == "anthropic"));
        assert!(seed.models.iter().any(|m| m.provider == "openai"));
        // All seed entries must be on the two filtered providers.
        for m in &seed.models {
            assert!(
                m.provider == "anthropic" || m.provider == "openai",
                "unexpected provider {} in seed",
                m.provider
            );
        }
        // Every override target must reference a real seed entry
        // before we try to apply it. This catches typos at test time.
        for entry in &overrides.overrides {
            assert!(
                seed.models
                    .iter()
                    .any(|m| m.provider == entry.target.provider && m.id == entry.target.id),
                "override target {}/{} does not match any seed entry",
                entry.target.provider,
                entry.target.id
            );
        }
    }

    /// Loading the registry from the bundled seed must succeed and the
    /// overrides must take effect.
    #[test]
    fn load_real_registry_applies_overrides() {
        let reg = ModelRegistry::load();
        assert!(!reg.providers().is_empty());
        // Pick a model the overrides file pins: opus-4-5 is a
        // pre-adaptive reasoning model, so the override forces adaptive
        // off. The refresh heuristic would otherwise default an
        // Anthropic reasoning model to adaptive on.
        if let Some(m) = reg.get("anthropic", "claude-opus-4-5") {
            assert!(
                !supports_adaptive_thinking(m),
                "opus-4-5 override should pin adaptive thinking off"
            );
        }
        // gpt-5.2 is a legacy budget? no — OpenAI model; just assert it
        // loads. Adaptive thinking is Anthropic-only.
        if let Some(m) = reg.get("openai", "gpt-5.2") {
            assert!(!supports_adaptive_thinking(m));
        }
    }

    /// The bundled Codex seed must parse and every entry must carry
    /// the expected provider id / api / base url. Misconfigured seed
    /// entries would silently hide Codex models from the picker, so
    /// pin the invariants here.
    #[test]
    fn bundled_codex_seed_well_formed() {
        let seed = bundled_codex_seed();
        assert!(!seed.is_empty(), "codex seed must be non-empty");

        // every codex entry shares the same fixed
        // provider/api/base_url triple.
        for m in &seed {
            assert_eq!(m.provider, CODEX_PROVIDER_ID);
            assert_eq!(m.api, "openai-codex-responses");
            assert_eq!(m.base_url, "https://chatgpt.com/backend-api");
            // max_tokens hard-coded at 128_000 across the
            // entire codex set.
            assert_eq!(m.max_tokens, 128_000);
        }

        // calls out the canonical id list; spot-check the
        // headline entries.
        let ids: std::collections::HashSet<&str> = seed.iter().map(|m| m.id.as_str()).collect();
        for expected in [
            "gpt-5.2",
            "gpt-5.4",
            "gpt-5.4-mini",
            "gpt-5.5",
            "gpt-5.6-sol",
            "gpt-5.6-terra",
            "gpt-5.6-luna",
        ] {
            assert!(ids.contains(expected), "codex seed missing {expected}");
        }

        // Context windows track the observed server cap per model, not the
        // marketing number: the gpt-5.6 family reports 372k, the rest sit at
        // the 272k cap.
        for m in &seed {
            let expected = match m.id.as_str() {
                "gpt-5.6-sol" | "gpt-5.6-terra" | "gpt-5.6-luna" => 372_000,
                _ => 272_000,
            };
            assert_eq!(
                m.context_window, expected,
                "unexpected context_window for {}",
                m.id
            );
        }

        // Only the gpt-5.6 family carries a context tier, and it fires
        // above 272k. The 272k-capped models must have no tiers: their
        // context can never strictly exceed the threshold, so a tier would
        // be dead config.
        for m in &seed {
            match m.id.as_str() {
                "gpt-5.6-sol" | "gpt-5.6-terra" | "gpt-5.6-luna" => {
                    assert_eq!(
                        m.cost.tiers.len(),
                        1,
                        "{} must have exactly one context tier",
                        m.id
                    );
                    assert_eq!(
                        m.cost.tiers[0].input_tokens_above, 272_000,
                        "{} tier threshold",
                        m.id
                    );
                }
                _ => assert!(
                    m.cost.tiers.is_empty(),
                    "{} must have no tiers (272k cap == threshold)",
                    m.id
                ),
            }
        }
    }

    /// `splice_codex_seed` must be additive only: entries already in
    /// the model list win over the seed so refreshed user caches
    /// aren't silently rewritten by the in-process seed.
    #[test]
    fn splice_codex_seed_is_additive_only() {
        let mut models = vec![ModelInfo {
            id: "gpt-5.5".into(),
            name: "gpt-5.5 (from cache)".into(),
            api: "openai-codex-responses".into(),
            provider: CODEX_PROVIDER_ID.into(),
            base_url: "https://chatgpt.com/backend-api".into(),
            reasoning: true,
            supports_adaptive_thinking: false,
            supports_verbosity: false,
            input: vec![InputModality::Text, InputModality::Image],
            cost: ModelCost {
                input: 9.99,
                output: 9.99,
                cache_read: 9.99,
                cache_write: 9.99,
                tiers: Vec::new(),
            },
            context_window: 272_000,
            max_tokens: 128_000,
            headers: None,
        }];

        let seed = bundled_codex_seed();
        let total_seed = seed.len();
        let appended = splice_codex_seed(&mut models, seed);

        // The seed entry for gpt-5.5 should not have been re-applied.
        assert_eq!(appended, total_seed - 1);
        assert_eq!(models.len(), total_seed);

        // The pre-existing entry's cost is preserved.
        let gpt55 = models
            .iter()
            .find(|m| m.id == "gpt-5.5")
            .expect("gpt-5.5 present");
        assert_eq!(gpt55.name, "gpt-5.5 (from cache)");
        assert!((gpt55.cost.input - 9.99).abs() < 1e-9);

        // A second splice with the same seed appends nothing.
        let appended_again = splice_codex_seed(&mut models, bundled_codex_seed());
        assert_eq!(appended_again, 0);
    }

    /// Non-codex entries in `codex.json` would be a maintainer
    /// mistake; the loader filters them out rather than letting them
    /// inject a foreign provider into the registry.
    #[test]
    fn splice_skips_non_codex_entries() {
        let stray = ModelInfo {
            id: "claude-zoo".into(),
            name: "Claude Zoo".into(),
            api: "anthropic-messages".into(),
            provider: "anthropic".into(),
            base_url: "https://api.anthropic.com".into(),
            reasoning: false,
            supports_adaptive_thinking: false,
            supports_verbosity: false,
            input: vec![InputModality::Text],
            cost: ModelCost::default(),
            context_window: 1,
            max_tokens: 1,
            headers: None,
        };
        let mut models = Vec::new();
        let appended = splice_codex_seed(&mut models, vec![stray]);
        // The splice accepts whatever the caller passes — filtering of
        // non-codex entries happens inside `bundled_codex_seed` before
        // the splice runs, not in the splice itself. Pin the splice's
        // behavior here so it doesn't grow surprising filters later.
        assert_eq!(appended, 1);
        assert_eq!(models.len(), 1);
    }

    /// `ModelRegistry::load()` must surface the Codex models, even
    /// when the bundled `models.json` snapshot predates the codex
    /// seed.
    #[test]
    fn load_surfaces_codex_models() {
        let reg = ModelRegistry::load();
        assert!(reg.providers().contains(&"openai-codex"));
        let codex = reg.models("openai-codex");
        assert!(!codex.is_empty());

        // gpt-5.5 is the canonical xhigh-capable, top-tier codex model.
        let gpt55 = reg
            .get("openai-codex", "gpt-5.5")
            .expect("gpt-5.5 present after load");
        assert!(gpt55.reasoning);
        assert!(!supports_adaptive_thinking(gpt55));
        assert_eq!(gpt55.api, "openai-codex-responses");
        assert_eq!(gpt55.base_url, "https://chatgpt.com/backend-api");
        assert_eq!(gpt55.context_window, 272_000);
        assert_eq!(gpt55.max_tokens, 128_000);
    }
}
