[package]
name = "aj"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
aj-agent = { path = "../aj-agent/" }
aj-conf = { path = "../aj-conf/" }
aj-tools = { path = "../aj-tools/" }
anthropic-sdk = { path = "../anthropic-sdk/" }
aj-ui = { path = "../aj-ui/" }
anyhow = { workspace = true }
console = { workspace = true }
dotenv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
