[package]
name = "aj"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
anthropic-sdk = { path = "../anthropic-sdk/" }

anyhow = { workspace = true }
dotenv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
nu-ansi-term = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
