[package]
name = "aj-tools"
version.workspace = true
edition.workspace = true

[[bin]]
name = "glob"
path = "src/bin/glob.rs"

[[bin]]
name = "grep"
path = "src/bin/grep.rs"

[dependencies]
anthropic-sdk = { path = "../anthropic-sdk/" }
aj-ui = { path = "../aj-ui/" }

anyhow = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
globset = { workspace = true }
grep = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
termimad = "0.33.0"
tokio = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
