[package]
name = "aj-tools"
version.workspace = true
edition.workspace = true

[[bin]]
name = "glob"
path = "src/bin/glob.rs"

[[bin]]
name = "grep"
path = "src/bin/grep.rs"

[dependencies]
anthropic-sdk = { path = "../anthropic-sdk/" }
aj-ui = { path = "../aj-ui/" }

anyhow = { workspace = true }
chrono = { workspace = true }
dotenv = { workspace = true }
futures = { workspace = true }
globset = { workspace = true }
grep = { workspace = true }
itertools = { workspace = true }
nu-ansi-term = { workspace = true }
regex = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
walkdir = { workspace = true }
