[package]
name = "aj-conf"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = "2.0"
chrono = { version = "0.4", features = ["serde"] }
tracing = { workspace = true }
schemars = { workspace = true }
